# In Class Notebook, Week 07

You can always paste the URL of this notebook (https://github.com/UIUC-iSchool-DataViz/is445_AOUAOG_fall2021/blob/master/week07/inClass_week07.ipynb ) into the nbviewer interface for a plain-text rendering:

https://kokes.github.io/nbviewer.js/viewer.html

In [10]:
# import our usual things
import pandas as pd
import bqplot
import numpy as np
import ipywidgets

## Review from last time

In [2]:
data3d = np.random.random((10,10,20))

In [3]:
data3d.shape

(10, 10, 20)

In [5]:
data3d[0,0,:]

array([0.54124828, 0.74085663, 0.09687062, 0.41278187, 0.86485492,
       0.83916209, 0.12256965, 0.29033369, 0.77222567, 0.56508207,
       0.90867493, 0.01965847, 0.20915492, 0.79891201, 0.63663157,
       0.95864038, 0.37553424, 0.16664989, 0.91251915, 0.58197625])

In [6]:
data3d.mean(axis=2)

array([[0.54071686, 0.55107975, 0.51234274, 0.5145504 , 0.46497102,
        0.42905291, 0.42656233, 0.49128036, 0.4054977 , 0.56155958],
       [0.46228498, 0.42338155, 0.59415794, 0.60819728, 0.56597605,
        0.51121569, 0.45792426, 0.61043616, 0.54714568, 0.58127305],
       [0.51397774, 0.52889253, 0.36980809, 0.52864474, 0.42484609,
        0.42711735, 0.56227841, 0.38661328, 0.65091268, 0.49966308],
       [0.43665654, 0.48015288, 0.46679803, 0.5792847 , 0.47955188,
        0.40715425, 0.50125869, 0.55210181, 0.46538023, 0.39810901],
       [0.52048808, 0.46948613, 0.57809338, 0.49964317, 0.48100504,
        0.4985754 , 0.54884247, 0.54509474, 0.545756  , 0.46683585],
       [0.46519147, 0.54068073, 0.5179983 , 0.41309053, 0.47186924,
        0.42179622, 0.62895304, 0.44321757, 0.55757922, 0.55300718],
       [0.46214573, 0.54584009, 0.57520554, 0.55510407, 0.57548104,
        0.47499138, 0.51263281, 0.49698276, 0.47479926, 0.53358586],
       [0.58795587, 0.54341188, 0.5574642

In [7]:
data3d.mean(axis=2).shape

(10, 10)

In [8]:
# 1. Data -- data3d

#2. Scales
col_sc = bqplot.ColorScale(scheme="Reds") 
x_sc = bqplot.OrdinalScale() # treating bins like bins of categorical data
y_sc = bqplot.OrdinalScale()

#3. Axis -- color & for x/y
ax_col = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
ax_x = bqplot.Axis(scale=x_sc)
ax_y = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark -- heatmap
heat_map = bqplot.GridHeatMap(color=data3d.mean(axis=2),
                             scales={'color':col_sc, 'row':y_sc, 'column':x_sc})

# 5. interactions around here -- in a moment!

# 6. Finally, put together figure
fig = bqplot.Figure(marks=[heat_map], axes=[ax_col, ax_x, ax_y])

# display!
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right'), Axis(scale=Ordi…

In [12]:
# 1. Data -- data3d

#2. Scales
col_sc = bqplot.ColorScale(scheme="Reds") 
x_sc = bqplot.OrdinalScale() # treating bins like bins of categorical data
y_sc = bqplot.OrdinalScale()

#3. Axis -- color & for x/y
ax_col = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
ax_x = bqplot.Axis(scale=x_sc)
ax_y = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark -- heatmap
heat_map = bqplot.GridHeatMap(color=data3d.mean(axis=2),
                             scales={'color':col_sc, 'row':y_sc, 'column':x_sc})

# 5. interactions around here -- in a moment!
mySelectedLabel = ipywidgets.Label()
mySelectedLabel.value = 'Mean selected point here'

# 6. Finally, put together figure
fig = bqplot.Figure(marks=[heat_map], axes=[ax_col, ax_x, ax_y])

# display!
#fig
myDashboard = ipywidgets.VBox([mySelectedLabel, fig])
myDashboard

In [13]:
# 1. Data -- data3d

#2. Scales
col_sc = bqplot.ColorScale(scheme="Reds") 
x_sc = bqplot.OrdinalScale() # treating bins like bins of categorical data
y_sc = bqplot.OrdinalScale()

#3. Axis -- color & for x/y
ax_col = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
ax_x = bqplot.Axis(scale=x_sc)
ax_y = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark -- heatmap
heat_map = bqplot.GridHeatMap(color=data3d.mean(axis=2),
                             scales={'color':col_sc, 'row':y_sc, 'column':x_sc})

# 5. interactions around here -- in a moment!
mySelectedLabel = ipywidgets.Label()
mySelectedLabel.value = 'Mean selected point here'
# interaction function -- what happens on selection:
def on_selected(change):
    print(change)
# link interaction function to my mark:
heat_map.observe(on_selected, 'selected')

# 6. Finally, put together figure
fig = bqplot.Figure(marks=[heat_map], axes=[ax_col, ax_x, ax_y])

# display!
#fig
myDashboard = ipywidgets.VBox([mySelectedLabel, fig])
myDashboard

In [15]:
# 1. Data -- data3d

#2. Scales
col_sc = bqplot.ColorScale(scheme="Reds") 
x_sc = bqplot.OrdinalScale() # treating bins like bins of categorical data
y_sc = bqplot.OrdinalScale()

#3. Axis -- color & for x/y
ax_col = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
ax_x = bqplot.Axis(scale=x_sc)
ax_y = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark -- heatmap
heat_map = bqplot.GridHeatMap(color=data3d.mean(axis=2),
                             scales={'color':col_sc, 'row':y_sc, 'column':x_sc}, 
                             interactions={'click':'select'})

# 5. interactions around here -- in a moment!
mySelectedLabel = ipywidgets.Label()
mySelectedLabel.value = 'Mean selected point here'
# interaction function -- what happens on selection:
def on_selected(change):
    print(change)
# link interaction function to my mark:
heat_map.observe(on_selected, 'selected')

# 6. Finally, put together figure
fig = bqplot.Figure(marks=[heat_map], axes=[ax_col, ax_x, ax_y])

# display!
#fig
myDashboard = ipywidgets.VBox([mySelectedLabel, fig])
myDashboard

{'name': 'selected', 'old': None, 'new': array([[8, 2]]), 'owner': GridHeatMap(color=array([[0.54071686, 0.55107975, 0.51234274, 0.5145504 , 0.46497102,
        0.42905291, 0.42656233, 0.49128036, 0.4054977 , 0.56155958],
       [0.46228498, 0.42338155, 0.59415794, 0.60819728, 0.56597605,
        0.51121569, 0.45792426, 0.61043616, 0.54714568, 0.58127305],
       [0.51397774, 0.52889253, 0.36980809, 0.52864474, 0.42484609,
        0.42711735, 0.56227841, 0.38661328, 0.65091268, 0.49966308],
       [0.43665654, 0.48015288, 0.46679803, 0.5792847 , 0.47955188,
        0.40715425, 0.50125869, 0.55210181, 0.46538023, 0.39810901],
       [0.52048808, 0.46948613, 0.57809338, 0.49964317, 0.48100504,
        0.4985754 , 0.54884247, 0.54509474, 0.545756  , 0.46683585],
       [0.46519147, 0.54068073, 0.5179983 , 0.41309053, 0.47186924,
        0.42179622, 0.62895304, 0.44321757, 0.55757922, 0.55300718],
       [0.46214573, 0.54584009, 0.57520554, 0.55510407, 0.57548104,
        0.47499138, 0.512

In [16]:
# 1. Data -- data3d

#2. Scales
col_sc = bqplot.ColorScale(scheme="Reds") 
x_sc = bqplot.OrdinalScale() # treating bins like bins of categorical data
y_sc = bqplot.OrdinalScale()

#3. Axis -- color & for x/y
ax_col = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
ax_x = bqplot.Axis(scale=x_sc)
ax_y = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark -- heatmap
heat_map = bqplot.GridHeatMap(color=data3d.mean(axis=2),
                             scales={'color':col_sc, 'row':y_sc, 'column':x_sc}, 
                             interactions={'click':'select'}, 
                             anchor_style={'fill':'blue'})

# 5. interactions around here -- in a moment!
mySelectedLabel = ipywidgets.Label()
mySelectedLabel.value = 'Mean selected point here'
# interaction function -- what happens on selection:
def on_selected(change):
    print(change)
# link interaction function to my mark:
heat_map.observe(on_selected, 'selected')

# 6. Finally, put together figure
fig = bqplot.Figure(marks=[heat_map], axes=[ax_col, ax_x, ax_y])

# display!
#fig
myDashboard = ipywidgets.VBox([mySelectedLabel, fig])
myDashboard

{'name': 'selected', 'old': None, 'new': array([[6, 4]]), 'owner': GridHeatMap(anchor_style={'fill': 'blue'}, color=array([[0.54071686, 0.55107975, 0.51234274, 0.5145504 , 0.46497102,
        0.42905291, 0.42656233, 0.49128036, 0.4054977 , 0.56155958],
       [0.46228498, 0.42338155, 0.59415794, 0.60819728, 0.56597605,
        0.51121569, 0.45792426, 0.61043616, 0.54714568, 0.58127305],
       [0.51397774, 0.52889253, 0.36980809, 0.52864474, 0.42484609,
        0.42711735, 0.56227841, 0.38661328, 0.65091268, 0.49966308],
       [0.43665654, 0.48015288, 0.46679803, 0.5792847 , 0.47955188,
        0.40715425, 0.50125869, 0.55210181, 0.46538023, 0.39810901],
       [0.52048808, 0.46948613, 0.57809338, 0.49964317, 0.48100504,
        0.4985754 , 0.54884247, 0.54509474, 0.545756  , 0.46683585],
       [0.46519147, 0.54068073, 0.5179983 , 0.41309053, 0.47186924,
        0.42179622, 0.62895304, 0.44321757, 0.55757922, 0.55300718],
       [0.46214573, 0.54584009, 0.57520554, 0.55510407, 0.5754

In [19]:
# 1. Data -- data3d

#2. Scales
col_sc = bqplot.ColorScale(scheme="Reds") 
x_sc = bqplot.OrdinalScale() # treating bins like bins of categorical data
y_sc = bqplot.OrdinalScale()

#3. Axis -- color & for x/y
ax_col = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
ax_x = bqplot.Axis(scale=x_sc)
ax_y = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark -- heatmap
heat_map = bqplot.GridHeatMap(color=data3d.mean(axis=2),
                             scales={'color':col_sc, 'row':y_sc, 'column':x_sc}, 
                             interactions={'click':'select'}, 
                             anchor_style={'fill':'blue'})

# 5. interactions around here -- in a moment!
mySelectedLabel = ipywidgets.Label()
mySelectedLabel.value = 'Mean selected point here'
# interaction function -- what happens on selection:
def on_selected(change):
    #print(change)
    if len(change['owner'].selected) == 1: # only allow user to select one bin
        i,j = change['owner'].selected[0] # the only selected bin
        print(i,j)
        v = data3d[i,j,:].mean() # mean of the 20 points in the 3rd dimension
        mySelectedLabel.value = 'Mean data value='+str(v)
# link interaction function to my mark:
heat_map.observe(on_selected, 'selected')

# 6. Finally, put together figure
fig = bqplot.Figure(marks=[heat_map], axes=[ax_col, ax_x, ax_y])

# display!
#fig
myDashboard = ipywidgets.VBox([mySelectedLabel, fig])
myDashboard

9 0
5 6
2 8


In [21]:
data3d[5,6,:].mean()

0.6289530435055469

Making a histogram with a "hard coded" i,j selection:

In [29]:
# 1. data
i,j = 1, 1
data3d[i,j,:]

array([0.65943914, 0.2114252 , 0.63698204, 0.18286158, 0.11954505,
       0.59477775, 0.8791518 , 0.06861093, 0.34076349, 0.51781035,
       0.40939074, 0.47589809, 0.96419257, 0.40555269, 0.27529985,
       0.14168981, 0.27349426, 0.53996642, 0.07503348, 0.6957457 ])

In [30]:
# 2. Scales -- linear for a histogram of numerical data
x_sch = bqplot.LinearScale()
y_sch = bqplot.LinearScale()

In [31]:
# 3. Axis
x_axh = bqplot.Axis(scale=x_sch, label='Value of 3rd Axis')
y_axh = bqplot.Axis(scale=y_sch, orientation='vertical', label='Frequency')

In [33]:
#bqplot.Hist?

In [36]:
# 4. Marks -- histogram, passing "sample" data attribute
hist = bqplot.Hist(sample=data3d[i,j,:], 
                  scales={'sample':x_sch, 'count':y_sch}, bins=5) # note: count is read-only

In [37]:
# 5. interactions could go here, BUT in this dashboard the interactions are being driven by the heat map

In [38]:
# 6. figure!
figh = bqplot.Figure(marks=[hist], axes=[x_axh, y_axh])
figh

Figure(axes=[Axis(label='Value of 3rd Axis', scale=LinearScale(), side='bottom'), Axis(label='Frequency', orie…

We need to do 2 things to finish our dashboard:
1. link the histogram to changes in our selection of the heatmap
2. display them side by side

In [39]:
# look at different attributes (like .value for our widget) that are in the hist mark:
hist.keys

['_model_module',
 '_model_module_version',
 '_model_name',
 '_view_count',
 '_view_module',
 '_view_module_version',
 '_view_name',
 'apply_clip',
 'bins',
 'colors',
 'count',
 'display_legend',
 'enable_hover',
 'interactions',
 'labels',
 'midpoints',
 'normalized',
 'opacities',
 'preserve_domain',
 'sample',
 'scales',
 'scales_metadata',
 'selected',
 'selected_style',
 'stroke',
 'tooltip',
 'tooltip_location',
 'tooltip_style',
 'unselected_style',
 'visible']

In [40]:
hist.sample # this is the attribute we want to change!

array([0.65943914, 0.2114252 , 0.63698204, 0.18286158, 0.11954505,
       0.59477775, 0.8791518 , 0.06861093, 0.34076349, 0.51781035,
       0.40939074, 0.47589809, 0.96419257, 0.40555269, 0.27529985,
       0.14168981, 0.27349426, 0.53996642, 0.07503348, 0.6957457 ])

In [41]:
# 1. Data -- data3d

#2. Scales
col_sc = bqplot.ColorScale(scheme="Reds") 
x_sc = bqplot.OrdinalScale() # treating bins like bins of categorical data
y_sc = bqplot.OrdinalScale()

#3. Axis -- color & for x/y
ax_col = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
ax_x = bqplot.Axis(scale=x_sc)
ax_y = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark -- heatmap
heat_map = bqplot.GridHeatMap(color=data3d.mean(axis=2),
                             scales={'color':col_sc, 'row':y_sc, 'column':x_sc}, 
                             interactions={'click':'select'}, 
                             anchor_style={'fill':'blue'})

# 5. interactions around here -- in a moment!
mySelectedLabel = ipywidgets.Label()
mySelectedLabel.value = 'Mean selected point here'
# interaction function -- what happens on selection:
def on_selected(change):
    #print(change)
    if len(change['owner'].selected) == 1: # only allow user to select one bin
        i,j = change['owner'].selected[0] # the only selected bin
        print(i,j)
        v = data3d[i,j,:].mean() # mean of the 20 points in the 3rd dimension
        mySelectedLabel.value = 'Mean data value='+str(v) # changing the attribute "value" of label widget
        # update histogram based on selection
        hist.sample = data3d[i,j,:]
# link interaction function to my mark:
heat_map.observe(on_selected, 'selected')

# 6. Finally, put together figure
fig = bqplot.Figure(marks=[heat_map], axes=[ax_col, ax_x, ax_y])

# display!
#fig
myDashboard = ipywidgets.VBox([mySelectedLabel, fig])
myDashboard

4 4
2 8
6 2


In [42]:
figh

Figure(axes=[Axis(label='Value of 3rd Axis', scale=LinearScale(), side='bottom'), Axis(label='Frequency', orie…

Display things together:

In [43]:
# side by side figures
figures = ipywidgets.HBox([fig, figh])

# label on top
myDashboard = ipywidgets.VBox([mySelectedLabel, figures])
myDashboard

7 9
7 6
5 5
6 3
8 3
9 1
4 3
2 6
2 8


In [ ]:
fig.layout.min_width='500px'