# In Class Notebook, Week 07

You can always paste the URL of this notebook (https://github.com/UIUC-iSchool-DataViz/is445_spring2022/blob/master/week07/inClass_week07.ipynb ) into the nbviewer interface for a plain-text rendering:

https://kokes.github.io/nbviewer.js/viewer.html

In [1]:
# import our usual things
import pandas as pd
import bqplot 
import numpy as np
import ipywidgets
import matplotlib.pyplot as plt

In [2]:
data = np.random.random((10,10,20))

In [3]:
data.shape

(10, 10, 20)

In [4]:
data[0,0,:]

array([0.07119276, 0.5339507 , 0.80583913, 0.80294036, 0.41181973,
       0.55648532, 0.81195724, 0.69063172, 0.21087759, 0.38714765,
       0.33739521, 0.91308073, 0.08896405, 0.45384509, 0.43151658,
       0.80063635, 0.07901114, 0.88916352, 0.50246675, 0.19728234])

In [5]:
myLabel = ipywidgets.Label()

In [10]:
myLabel.value = str(data[0,0,:].mean())

In [9]:
myLabel

Label(value='[[0.4988102  0.50040233 0.60487685 0.52798817 0.56697864 0.56730042\n  0.58249943 0.51037515 0.60…

In [11]:
data.mean(axis=2).shape # taking a mean along the "Z" or "3rd" axis

(10, 10)

In [14]:
data.mean(axis=0).shape

(10, 20)

In [15]:
data.mean(axis=1).shape

(10, 20)

In [12]:
# reminder of what a "on selection" function looks like
def on_selected(change):
    #print(change)
    #print(change['owner'])
    if len(change['owner'].selected) == 1: # only allow user to select one bin at a time
        i,j = change['owner'].selected[0]
        print(i,j)

In [13]:
# 1. data (random dataset)

#2. Scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. axis
ax_col = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
ax_x = bqplot.Axis(scale=x_sc)
ax_y = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark (heatmap)
heat_map = bqplot.GridHeatMap(color=data.mean(axis=2),
                              scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                              interactions={'click':'select'},
                              selected_style={'fill':'magenta'})

# 5. interaction, cont.
heat_map.observe(on_selected,'selected')

# combine into a figure
fig = bqplot.Figure(marks=[heat_map],axes=[ax_col, ax_x, ax_y])

# Finally dashboard
myDashboard = ipywidgets.VBox([myLabel,fig])
myDashboard

5 2
1 1
2 3
0 0
0 1
0 2


In [16]:
# reminder of what a "on selection" function looks like
def on_selected(change):
    #print(change)
    #print(change['owner'])
    if len(change['owner'].selected) == 1: # only allow user to select one bin at a time
        i,j = change['owner'].selected[0]
        #print(i,j)
        v = data[i,j,:].mean()
        myLabel.value = 'Mean Data Value for Selection=' + str(v)

In [17]:
# 1. data (random dataset)

#2. Scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. axis
ax_col = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
ax_x = bqplot.Axis(scale=x_sc)
ax_y = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark (heatmap)
heat_map = bqplot.GridHeatMap(color=data.mean(axis=2),
                              scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                              interactions={'click':'select'},
                              selected_style={'fill':'magenta'})

# 5. interaction, cont.
heat_map.observe(on_selected,'selected')

# combine into a figure
fig = bqplot.Figure(marks=[heat_map],axes=[ax_col, ax_x, ax_y])

# Finally dashboard
myDashboard = ipywidgets.VBox([myLabel,fig])
myDashboard

In [18]:
# 1. data
i,j=0,0

data[i,j,:]

array([0.07119276, 0.5339507 , 0.80583913, 0.80294036, 0.41181973,
       0.55648532, 0.81195724, 0.69063172, 0.21087759, 0.38714765,
       0.33739521, 0.91308073, 0.08896405, 0.45384509, 0.43151658,
       0.80063635, 0.07901114, 0.88916352, 0.50246675, 0.19728234])

In [19]:
# 2. scales
x_sch = bqplot.LinearScale()
y_sch = bqplot.LinearScale()

# 3. Axis
x_axh = bqplot.Axis(scale=x_sch, label='Value of 3rd Axis')
y_axh = bqplot.Axis(scale=y_sch, label='Frequency', orientation='vertical')

In [20]:
bqplot.Hist?

In [21]:
# 4. Mark
hist = bqplot.Hist(sample=data[i,j,:], scales={'sample':x_sch, 'count':y_sch}, bins=5)

In [22]:
# 5. Interactions here (but none yet!)

# finally a figure
figh = bqplot.Figure(marks=[hist], axes=[x_axh, y_axh])
figh

Figure(axes=[Axis(label='Value of 3rd Axis', scale=LinearScale(), side='bottom'), Axis(label='Frequency', orie…

In [23]:
hist.keys

['_model_module',
 '_model_module_version',
 '_model_name',
 '_view_count',
 '_view_module',
 '_view_module_version',
 '_view_name',
 'apply_clip',
 'bins',
 'colors',
 'count',
 'display_legend',
 'enable_hover',
 'interactions',
 'labels',
 'midpoints',
 'normalized',
 'opacities',
 'preserve_domain',
 'sample',
 'scales',
 'scales_metadata',
 'selected',
 'selected_style',
 'stroke',
 'tooltip',
 'tooltip_location',
 'tooltip_style',
 'unselected_style',
 'visible']

In [24]:
hist.sample

array([0.07119276, 0.5339507 , 0.80583913, 0.80294036, 0.41181973,
       0.55648532, 0.81195724, 0.69063172, 0.21087759, 0.38714765,
       0.33739521, 0.91308073, 0.08896405, 0.45384509, 0.43151658,
       0.80063635, 0.07901114, 0.88916352, 0.50246675, 0.19728234])

In [25]:
# ######### GRID HEAT MAP #########
# Left, the driver of changes

#2. Scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. axis
ax_col = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
ax_x = bqplot.Axis(scale=x_sc)
ax_y = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark (heatmap)
heat_map = bqplot.GridHeatMap(color=data.mean(axis=2),
                              scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                              interactions={'click':'select'},
                              selected_style={'fill':'magenta'})

# 5. interaction, cont.
######heat_map.observe(on_selected,'selected')

# combine into a figure
fig = bqplot.Figure(marks=[heat_map],axes=[ax_col, ax_x, ax_y])

In [26]:
########## HISTOGRAM ########
# 2. scales
x_sch = bqplot.LinearScale()
y_sch = bqplot.LinearScale()

# 3. Axis
x_axh = bqplot.Axis(scale=x_sch, label='Value of 3rd Axis')
y_axh = bqplot.Axis(scale=y_sch, label='Frequency', orientation='vertical')

# 4. Mark
hist = bqplot.Hist(sample=data[i,j,:], scales={'sample':x_sch, 'count':y_sch}, bins=5)

# finally a figure
figh = bqplot.Figure(marks=[hist], axes=[x_axh, y_axh])

In [27]:
myLabel = ipywidgets.Label()

In [28]:
# Function defining interactions between all dashboard elements
def on_selected(change):
    if len(change['owner'].selected) == 1: # only allow user to select one bin at a time
        i,j = change['owner'].selected[0]
        v = data[i,j,:].mean()
        myLabel.value = 'Mean Data Value for Selection=' + str(v)
        hist.sample = data[i,j,:]

In [29]:
# make sure we have heatmap OBSERVE with this function
heat_map.observe(on_selected, 'selected')

In [33]:
# make a dashboard!
fig.layout.min_width='400px'
figh.layout.min_width='400px'

figures = ipywidgets.HBox([fig,figh])
myDashboard = ipywidgets.VBox([myLabel, figures])
myDashboard

In [35]:
hist.keys

['_model_module',
 '_model_module_version',
 '_model_name',
 '_view_count',
 '_view_module',
 '_view_module_version',
 '_view_name',
 'apply_clip',
 'bins',
 'colors',
 'count',
 'display_legend',
 'enable_hover',
 'interactions',
 'labels',
 'midpoints',
 'normalized',
 'opacities',
 'preserve_domain',
 'sample',
 'scales',
 'scales_metadata',
 'selected',
 'selected_style',
 'stroke',
 'tooltip',
 'tooltip_location',
 'tooltip_style',
 'unselected_style',
 'visible']