# Quick review from last time (starting to dashboard)

In [1]:
# importing our usual stuff
import pandas as pd
import bqplot
import numpy as np
import ipywidgets
import matplotlib.pyplot as plt

In [2]:
data = np.random.random((10,10,20))

In [4]:
data[0,0,:]

array([0.40106314, 0.35194486, 0.56792231, 0.63369646, 0.11737582,
       0.11811055, 0.08579615, 0.72730843, 0.25164027, 0.38346471,
       0.52436843, 0.01425893, 0.56597883, 0.45926439, 0.5043769 ,
       0.55201063, 0.60028744, 0.5000412 , 0.91977477, 0.22437204])

In [5]:
data.mean(axis=2)

array([[0.42515281, 0.44192377, 0.4314524 , 0.55520703, 0.44775511,
        0.43639444, 0.63699249, 0.56765222, 0.37998332, 0.48656082],
       [0.51588198, 0.53461363, 0.52339502, 0.58290146, 0.44114441,
        0.56483969, 0.36392696, 0.51284449, 0.47803579, 0.46828314],
       [0.50246825, 0.52051466, 0.44587837, 0.53901182, 0.56252309,
        0.54442534, 0.59682264, 0.50144385, 0.43820362, 0.5411583 ],
       [0.44234705, 0.46253566, 0.52146916, 0.46134276, 0.55770367,
        0.45813336, 0.48614609, 0.53391371, 0.47235486, 0.53888472],
       [0.60709151, 0.54274907, 0.46528136, 0.430033  , 0.53206441,
        0.63815627, 0.58208766, 0.58328135, 0.47114623, 0.47036821],
       [0.5097685 , 0.53836904, 0.45565626, 0.5452331 , 0.55934413,
        0.4895886 , 0.28211926, 0.56618729, 0.52845454, 0.50247121],
       [0.68223912, 0.56045495, 0.55635988, 0.47410131, 0.57066657,
        0.52922983, 0.55769776, 0.64704773, 0.5254286 , 0.57150719],
       [0.42711862, 0.62565902, 0.4719023

In [6]:
data.mean(axis=2).shape

(10, 10)

Built up a dashboard with:
 1. label showing the mean at a selected grid (on top of everything)
 1. on the left was the grid heatmap built from the mean along the 3rd axis
 1. on the right was a histogram of the 3rd axis's points (of a selected grid)

In [7]:
mySelectedLabel = ipywidgets.Label()

In [10]:
# 1. Data -- 3D data, created above

# 2. Scales
x_sc = bqplot.OrdinalScale() # categorical data
y_sc = bqplot.OrdinalScale()
col_sc = bqplot.ColorScale(scheme='Reds')

# 3. Axes
ax_x = bqplot.Axis(scale=x_sc)
ax_y = bqplot.Axis(scale=y_sc, orientation='vertical')
ax_col = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right') # colorbar

# 4. Mark (gridheat map)
heat_map = bqplot.GridHeatMap(color=data.mean(axis=2),
                             scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'}, # on clicking on a grid, select that grid
                             anchor_style={'fill':'blue'}, # turn the grid blue on selection
                             selected_style={'opacity':1.0}, # selected grid is fully opaque on selection,
                             unselected_style={'opacity':0.8}) # otherwise, a little see-through

# 5. Interactions (also in step 4 as well)
def on_selected(change):
    if len(change['owner'].selected) == 1: # forcing only selection of 1 grid
        i,j = change['owner'].selected[0] # only 1 selection
        v = data[i,j,:].mean() # value of mean of the data at the i,j grid
        mySelectedLabel.value = 'Mean data value =' + str(v)
# don't forget the actual linking!
heat_map.observe(on_selected,'selected') # linking the selected trait of the heat_map with the on_selected function
        

# All together -- a figure!
fig = bqplot.Figure(marks=[heat_map], axes=[ax_col, ax_x, ax_y])

myDashboard = ipywidgets.VBox([mySelectedLabel, fig])
myDashboard

In [11]:
# 1. Data for histogram
# first hard-coding the data for the histogram
i,j = 0,0
data[i,j]

array([0.40106314, 0.35194486, 0.56792231, 0.63369646, 0.11737582,
       0.11811055, 0.08579615, 0.72730843, 0.25164027, 0.38346471,
       0.52436843, 0.01425893, 0.56597883, 0.45926439, 0.5043769 ,
       0.55201063, 0.60028744, 0.5000412 , 0.91977477, 0.22437204])

In [12]:
# 2. scales for histogram
x_sch = bqplot.LinearScale()
y_sch = bqplot.LinearScale()

In [13]:
# 3. Axis for histogram
x_axh = bqplot.Axis(scale=x_sch, label='Value of 3rd Axis')
y_axh = bqplot.Axis(scale=y_sch, label='Freq', orientation='vertical')

In [14]:
# 4. Marks -- histogram mark
hist = bqplot.Hist(sample=data[i,j,:], normalized=False, scales={'sample':x_sch, 'count':y_sch}, bins=5)

In [15]:
# figure!
figh = bqplot.Figure(marks=[hist], axes=[x_axh, y_axh])
figh

Figure(axes=[Axis(label='Value of 3rd Axis', scale=LinearScale(), side='bottom'), Axis(label='Freq', orientati…

Finally, linking between the GridHeatMap mark and the histogram mark:

In [19]:
# 1. Data -- 3D data, created above

# 2. Scales
x_sc = bqplot.OrdinalScale() # categorical data
y_sc = bqplot.OrdinalScale()
col_sc = bqplot.ColorScale(scheme='Reds')

# 3. Axes
ax_x = bqplot.Axis(scale=x_sc)
ax_y = bqplot.Axis(scale=y_sc, orientation='vertical')
ax_col = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right') # colorbar

# 4. Mark (gridheat map)
heat_map = bqplot.GridHeatMap(color=data.mean(axis=2),
                             scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'}, # on clicking on a grid, select that grid
                             anchor_style={'fill':'blue'}, # turn the grid blue on selection
                             selected_style={'opacity':1.0}, # selected grid is fully opaque on selection,
                             unselected_style={'opacity':0.8}) # otherwise, a little see-through

# 5. Interactions (also in step 4 as well)
def on_selected(change):
    if len(change['owner'].selected) == 1: # forcing only selection of 1 grid
        i,j = change['owner'].selected[0] # only 1 selection
        v = data[i,j,:].mean() # value of mean of the data at the i,j grid
        mySelectedLabel.value = 'Mean data value =' + str(v)
        # including link with the histogram
        hist.sample = data[i,j,:]# don't forget the actual linking!
heat_map.observe(on_selected,'selected') # linking the selected trait of the heat_map with the on_selected function
        

# All together -- a figure!
fig = bqplot.Figure(marks=[heat_map], axes=[ax_col, ax_x, ax_y])

#myDashboard = ipywidgets.VBox([mySelectedLabel, fig])
fig.layout.min_width='400px'
figh.layout.min_width='400px'
figures = ipywidgets.HBox([fig,figh])
myDashboard = ipywidgets.VBox([mySelectedLabel, figures])

myDashboard

# Another dashboard with the UFO dataset

In [20]:
ufos = pd.read_csv("ufo-scrubbed-geocoded-time-standardized-00.csv",
                  names = ["date", "city", "state", "country",
                          "shape", "duration_seconds", "duration",
                          "comment", "report_date", 
                           "latitude", "longitude"],
                  parse_dates = ["date", "report_date"])

In [21]:
ufos

date                  city state country     shape  \
0     1949-10-10 20:30:00            san marcos    tx      us  cylinder   
1     1949-10-10 21:00:00          lackland afb    tx     NaN     light   
2     1955-10-10 17:00:00  chester (uk/england)   NaN      gb    circle   
3     1956-10-10 21:00:00                  edna    tx      us    circle   
4     1960-10-10 20:00:00               kaneohe    hi      us     light   
...                   ...                   ...   ...     ...       ...   
80327 2013-09-09 21:15:00             nashville    tn      us     light   
80328 2013-09-09 22:00:00                 boise    id      us    circle   
80329 2013-09-09 22:00:00                  napa    ca      us     other   
80330 2013-09-09 22:20:00                vienna    va      us    circle   
80331 2013-09-09 23:00:00                edmond    ok      us     cigar   

       duration_seconds    duration  \
0                2700.0  45 minutes   
1                7200.0     1-2 hrs   
2                  20.0  20 seconds   
3                  20.0    1/2 hour   
4                 900.0  15 minutes   
...                 ...         ...   
80327             600.0  10 minutes   
80328            1200.0  20 minutes   
80329            1200.0        hour   
80330               5.0   5 seconds   
80331            1020.0  17 minutes   

                                                 comment report_date  \
0      This event took place in early fall around 194...  2004-04-27   
1      1949 Lackland AFB&#44 TX.  Lights racing acros...  2005-12-16   
2      Green/Orange circular disc over Chester&#44 En...  2008-01-21   
3      My older brother and twin sister were leaving ...  2004-01-17   
4      AS a Marine 1st Lt. flying an FJ4B fighter/att...  2004-01-22   
...                                                  ...         ...   
80327  Round from the distance/slowly changing colors...  2013-09-30   
80328  Boise&#44 ID&#44 spherical&#44 20 min&#44 10 r...  2013-09-30   
80329                                       Napa UFO&#44  2013-09-30   
80330  Saw a five gold lit cicular craft moving fastl...  2013-09-30   
80331  2 witnesses 2  miles apart&#44 Red &amp; White...  2013-09-30   

        latitude   longitude  
0      29.883056  -97.941111  
1      29.384210  -98.581082  
2      53.200000   -2.916667  
3      28.978333  -96.645833  
4      21.418056 -157.803611  
...          ...         ...  
80327  36.165833  -86.784444  
80328  43.613611 -116.202500  
80329  38.297222 -122.284444  
80330  38.901111  -77.265556  
80331  35.652778  -97.477778  

[80332 rows x 11 columns]

In [22]:
len(ufos)

80332

A reminder for large datasets:

In [23]:
nsamples = 1000
downSampleInds = np.random.choice(range(len(ufos)-1), nsamples, replace=False)
downSampleInds

array([74113, 37754, 59913, 20978, 24647, 41601, 62485,  4087, 42090,
       31121,  5024, 18616, 16503, 62346, 12396, 10746,  9625, 51808,
       76128, 28066, 49676,  7194,  7780, 63885, 79542, 68178,   462,
       32828, 27442, 50306, 74283, 31225,  3466,  9208, 24181, 38272,
        4154, 52685, 23749, 28756, 17443, 18026, 47108, 38354, 47427,
       79042, 46795, 76741,  9641, 58290, 28172, 15066, 68686,  5601,
       64388, 23438, 64636, 16615, 14955, 80106, 32804, 20460, 40970,
       54937, 23436, 46121,  5385,  9052, 17021, 50120, 46792,  8144,
       18208, 48674, 40293, 74324, 70788, 43205, 41949, 37667, 21816,
       40358, 66521, 22084, 66449, 44650, 66022, 75132, 78019, 42241,
       64401, 13650, 47148, 37692, 18085, 72146, 78969, 72770, 28184,
       66231, 26558, 64207, 14240, 13301, 23177, 64199,  9523, 20507,
       40718,   960, 18854, 29382, 10997,  5717, 25301, 67284, 41366,
       47183, 70252, 56164, 30570, 55405, 12404, 35158, 28403, 74799,
       46474, 17671,

In [24]:
ufosDS = ufos.loc[downSampleInds]

In [25]:
ufosDS

date                      city state country     shape  \
74113 2002-09-13 20:30:00                       jal    nm      us     light   
37754 2007-04-19 23:00:00                greenville    mi      us     light   
59913 2004-07-26 05:25:00      mississauga (canada)    on      ca      disk   
20978 2000-12-28 17:09:00                   houston    tx      us     light   
24647 2014-01-04 23:30:00                  clermont    fl      us  triangle   
...                   ...                       ...   ...     ...       ...   
6715  2006-10-06 19:00:00             fes (morocco)   NaN     NaN    circle   
11611 2005-11-20 22:35:00     melbourne (australia)   NaN      au     light   
8905  2004-11-13 22:30:00               circleville    oh      us     light   
76300 1999-09-21 18:00:00                 san diego    ca      us    circle   
22477 1985-12-05 05:00:00  manaus-amazonas (brazil)    al     NaN       egg   

       duration_seconds     duration  \
74113               5.0    5 seconds   
37754             900.0      15 min.   
59913            1200.0      20 mins   
20978             660.0   11 minutes   
24647              15.0   15 seconds   
...                 ...          ...   
6715              120.0    2 minutes   
11611            2700.0      >45mins   
8905              120.0     1-2 min.   
76300               1.5  1.5 seconds   
22477             600.0        10:00   

                                                 comment report_date  \
74113  Fast Moving object...Traveling from South to N...  2002-09-19   
37754  strange neon color lights come together as one...  2007-04-27   
59913  I saw coloured lights in the sky outside throu...  2004-08-11   
20978  Bright&#44 burning&#44 descending small&#44 na...  2001-01-03   
24647  Very low slow triangular craft with bright whi...  2014-01-10   
...                                                  ...         ...   
6715   Looking off balcony at night sky curious becau...  2006-12-07   
11611  3 lighted spherical UFO seen over the eastern ...  2005-12-16   
8905   Fire colored orange lights spotted in Circlevi...  2006-02-14   
76300  Ilooked up saw circular object with 3 whitish ...  2003-11-11   
22477  this case happen to me and my brother my engli...  2007-08-07   

        latitude   longitude  
74113  32.113056 -103.193056  
37754  43.177500  -85.252778  
59913  43.150000  -79.500000  
20978  29.763056  -95.363056  
24647  28.549167  -81.773056  
...          ...         ...  
6715   34.033333   -5.000000  
11611 -37.813938  144.963425  
8905   39.600556  -82.946111  
76300  32.715278 -117.156389  
22477  -3.086529  -60.052321  

[1000 rows x 11 columns]

A quick bqplot of the ufo(DS) dataset using a scatter plot:

In [32]:
# 2. Scales
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()
c_sc = bqplot.ColorScale()

# 3. Axis
x_ax = bqplot.Axis(scale=x_sc, label='Longitude')
y_ax = bqplot.Axis(scale=y_sc, label='Latitude', orientation='vertical')
c_ax = bqplot.ColorAxis(scale=c_sc, orientation='vertical', side='right')

# 4. Marks
scatters = bqplot.Scatter(x=ufosDS['longitude'], y=ufosDS['latitude'],
                          color=np.log10(ufosDS['duration_seconds']),
                         scales={'x':x_sc, 'y':y_sc, 'color':c_sc})

# put together in a figure
fig = bqplot.Figure(marks=[scatters], axes=[x_ax, y_ax, c_ax])
fig

Figure(axes=[Axis(label='Longitude', scale=LinearScale()), Axis(label='Latitude', orientation='vertical', scal…

In [31]:
ufosDS['duration_seconds'].min(), ufosDS['duration_seconds'].max()

(1.0, 432000.0)

# UFO dataset with a GridHeatMap and some 2d histogramming

Order of operations:
 1. Choose the bins in long/lat
 1. Make a 2d histogram with NumPy
 1. Choose a weight (color -- duration in seconds)
 1. Log of the color
 1. Calculate the bin-centers for plotting

In [50]:
def generate_histogram_from_lat_long(ufos, nlong=20, nlat=20, longmin=-150, longmax=150,
                                     latmin=-40, latmax=70,
                                     takeLog=True):
    long_bins = np.linspace(longmin, longmax, nlong+1) # longitude bins
    lat_bins = np.linspace(latmin, latmax, nlat+1) # latitude bins
    # using NumPy 2D histogram to bin the data in 2D
    hist2d, long_edges, lat_edges = np.histogram2d(ufos['longitude'], 
                                                   ufos['latitude'], 
                                                   weights=ufos['duration_seconds'], # weighted by duration in seconds
                                                  bins = [long_bins,lat_bins])
    hist2d = hist2d.T # transpose because of default binning
    if takeLog: # log10 transformation of the colormap
        hist2d[hist2d <= 0] = np.nan # set zeros to NaNs
        # then take log
        hist2d = np.log10(hist2d)
    long_centers = (long_edges[:-1] + long_edges[1:]) / 2 # inline programming to get bin centers
    lat_centers = (lat_edges[:-1] + lat_edges[1:]) / 2 # same thing here
    return hist2d, long_centers, lat_centers, long_edges, lat_edges

In [52]:
hist2d, long_centers, lat_centers, long_edges, lat_edges = generate_histogram_from_lat_long(ufos)

In [36]:
hist2d

array([[       nan,        nan,        nan,        nan,        nan,
        3.15836249, 4.95777963,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,
               nan,        nan, 2.78887512,        nan, 5.1441975 ],
       [       nan,        nan,        nan,        nan,        nan,
        4.21512208, 3.06818586,        nan,        nan,        nan,
               nan, 4.45993502, 4.45336421,        nan,        nan,
        3.78283081,        nan, 4.88131902, 3.06445799, 4.02816442],
       [       nan,        nan, 0.        ,        nan,        nan,
        3.8920946 , 4.78334607,        nan,        nan,        nan,
               nan, 4.42499591, 3.34635297,        nan,        nan,
               nan,        nan, 3.20139712, 4.39578055, 3.17897695],
       [       nan,        nan,        nan,        nan,        nan,
        3.68124124, 4.00121433, 4.08278537,        nan,        nan,
        2.07918125, 3.78426058,        nan, 3

In [37]:
long_centers

array([-142.5, -127.5, -112.5,  -97.5,  -82.5,  -67.5,  -52.5,  -37.5,
        -22.5,   -7.5,    7.5,   22.5,   37.5,   52.5,   67.5,   82.5,
         97.5,  112.5,  127.5,  142.5])

In [38]:
lat_centers

array([-37.25, -31.75, -26.25, -20.75, -15.25,  -9.75,  -4.25,   1.25,
         6.75,  12.25,  17.75,  23.25,  28.75,  34.25,  39.75,  45.25,
        50.75,  56.25,  61.75,  67.25])

In [40]:
# 1. Data -- 2d histogram in lat/long

# 2. Scales
# x/y
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()
col_sc = bqplot.ColorScale(scheme='RdPu')

# 3. Axis -- x/y AND color
x_ax = bqplot.Axis(scale=x_sc, label='Longitude')
y_ax = bqplot.Axis(scale=y_sc, label='Latitude', orientation='vertical')
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')

# 4. Marks
heat_map = bqplot.GridHeatMap(color=hist2d, row=lat_centers, column=long_centers, 
                             scales={'color':col_sc, 'row':y_sc, 'column':x_sc})

# 5. Interations -- none just yet!

# Put it together as a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, y_ax, x_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='RdPu'), side='right'), Axis(label='Lat…

In [41]:
# 1. Data -- 2d histogram in lat/long

# 2. Scales
# x/y
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()
col_sc = bqplot.ColorScale(scheme='RdPu')

# 3. Axis -- x/y AND color
x_ax = bqplot.Axis(scale=x_sc, label='Longitude')
y_ax = bqplot.Axis(scale=y_sc, label='Latitude', orientation='vertical')
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')

# 4. Marks
heat_map = bqplot.GridHeatMap(color=hist2d, row=lat_centers, column=long_centers, 
                             scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'}, # select on click
                             anchor_style={'fill':'blue'}, # fill selection with blue
                             selected_style={'opacity':1.0}, # opaque on selection
                             unselected_style={'opacity':0.8}) # see-through for non-selected

# 5. Interations -- none just yet!

# Put it together as a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, y_ax, x_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='RdPu'), side='right'), Axis(label='Lat…

Looking forward -- we want to have a label on top again, and a plot on the right that is being driven by our selections on our gridheatmap on the left.

In [44]:
# 1. Data -- 2d histogram in lat/long

# 2. Scales
# x/y
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()
col_sc = bqplot.ColorScale(scheme='RdPu')

# 3. Axis -- x/y AND color
x_ax = bqplot.Axis(scale=x_sc, label='Longitude')
y_ax = bqplot.Axis(scale=y_sc, label='Latitude', orientation='vertical')
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')

# 4. Marks
heat_map = bqplot.GridHeatMap(color=hist2d, row=lat_centers, column=long_centers, 
                             scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'}, # select on click
                             anchor_style={'fill':'blue'}, # fill selection with blue
                             selected_style={'opacity':1.0}, # opaque on selection
                             unselected_style={'opacity':0.8}) # see-through for non-selected

# 5. Interations -- first adding a label
mySelectedLabel = ipywidgets.Label()
# 5.1 on selection function
def on_selection(change):
    #print(change)
    #print(change['owner'])
    #print(change['owner'].selected)
    if len(change['owner'].selected) == 1: # allowing only 1 selection
        i,j = change['owner'].selected[0]
        v = hist2d[i,j] # grab data value
        mySelectedLabel.value = 'Total duration in sum(log(sec))=' + str(v) # set label
        
# 5.2 linking of the heatmap traits with this function
heat_map.observe(on_selection,'selected')

# Put it together as a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, y_ax, x_ax])
#fig
myDashboard = ipywidgets.VBox([mySelectedLabel, fig])
myDashboard

Before: we plotted a histogram of the distribution of values along the 3rd axis.

This time: we'll use this selected grid to subset/mask our data and plot other attributes on a 2nd plot on the right -- specificically, looking at a scatter plot of the log(duration_seconds) as a function of the date of the observation.

In [45]:
import datetime as dt # for formatting our "date" data

In [46]:
# 2. Scales -- date-time scale
x_scl = bqplot.DateScale(min=dt.datetime(1950,1,1), max=dt.datetime(2021,1,1)) # formatting for x-scale

In [47]:
y_scl = bqplot.LogScale() # taking log on "viz engine side" not on the data-side this time

In [48]:
# 3. Axis
ax_xcl = bqplot.Axis(label='Date',scale=x_scl)
ax_ycl = bqplot.Axis(label='Duration in Seconds', scale=y_scl, orientation='vertical', side='left')

We need to do an extra step to go from indices to a subset condition for data values:

In [53]:
i,j = 19,0 # for-though, I know this bin has data!

In [54]:
longs = [long_edges[j], long_edges[j+1]]

In [55]:
longs

[-150.0, -135.0]

In [56]:
lats = [lat_edges[i], lat_edges[i+1]]

In [57]:
lats

[64.5, 70.0]

Create mask based on these long & lat conditions:

In [58]:
region_mask = ( (ufos['latitude'] >= lats[0]) & (ufos['latitude']<=lats[1]) &\
              (ufos['longitude'] >= longs[0]) & (ufos['longitude']<=longs[1]))

In [59]:
ufos['latitude'][region_mask]

327      64.837778
2845     64.837778
3620     64.837778
4602     64.751111
6011     64.837778
           ...    
77347    64.751111
77497    64.837778
78571    64.837778
79029    64.837778
79470    64.837778
Name: latitude, Length: 74, dtype: float64

In [60]:
ufos.loc[region_mask]

date        city state country    shape  \
327   2001-10-11 02:15:00   fairbanks    ak      us    other   
2845  2012-10-18 21:30:00   fairbanks    ak      us    light   
3620  2000-10-02 23:00:00   fairbanks    ak      us      NaN   
4602  2012-10-25 23:00:00  north pole    ak      us    light   
6011  2013-10-31 20:30:00   fairbanks    ak      us  diamond   
...                   ...         ...   ...     ...      ...   
77347 1998-09-24 22:35:00  north pole    ak      us   sphere   
77497 2013-09-24 20:35:00   fairbanks    ak      us   circle   
78571 2013-09-29 21:30:00   fairbanks    ak      us    light   
79029 2012-09-03 21:57:00   fairbanks    ak      us  unknown   
79470 2013-09-05 22:00:00   fairbanks    ak      us     disk   

       duration_seconds      duration  \
327              1800.0    30 minutes   
2845              600.0  5-10 minutes   
3620              300.0          hour   
4602               15.0    15 seconds   
6011              180.0     3 minutes   
...                 ...           ...   
77347             600.0    10 minutes   
77497             120.0    ~2 minutes   
78571             420.0   5-7 minutes   
79029             120.0     2 minutes   
79470             300.0     5 minutes   

                                                 comment report_date  \
327    It looked like a star but it would move and af...  2001-10-12   
2845   Changing light from bright to dim&#44 to off t...  2012-10-30   
3620   Lights gradually coming on&#44 and then going ...  2002-12-23   
4602   It was late at night and me and my mother were...  2012-12-20   
6011          UFO seen over civilian side of Birch Hill.  2013-11-11   
...                                                  ...         ...   
77347  Two Orange sphere appeared low on horizon just...  1998-09-26   
77497                 3 white orbs. 2 in front 1 behind.  2013-09-30   
78571           2 orange orbs fly south over chena ridge  2013-09-30   
79029  Metallic sounds and bright flash of light - Se...  2012-09-24   
79470             HUGE SAUCER FLYING INTO FORT WAINRIGHT  2013-09-30   

        latitude   longitude  
327    64.837778 -147.716389  
2845   64.837778 -147.716389  
3620   64.837778 -147.716389  
4602   64.751111 -147.349444  
6011   64.837778 -147.716389  
...          ...         ...  
77347  64.751111 -147.349444  
77497  64.837778 -147.716389  
78571  64.837778 -147.716389  
79029  64.837778 -147.716389  
79470  64.837778 -147.716389  

[74 rows x 11 columns]

In [61]:
# 4. Marks
duration_scatter = bqplot.Scatter(x=ufos['date'][region_mask],
                                 y=ufos['duration_seconds'][region_mask],
                                 scales={'x':x_scl, 'y':y_scl})

In [62]:
# Put together in figure!
fig_dur = bqplot.Figure(marks=[duration_scatter], axes=[ax_xcl, ax_ycl])
fig_dur

Figure(axes=[Axis(label='Date', scale=DateScale(max=datetime.datetime(2021, 1, 1, 0, 0), min=datetime.datetime…

Put the grid heatmap on the right and have it "drive" changes on the left scatter plot as a dashboard:

In [70]:
### (I) GRID HEAT MAP
# 1. Data -- 2d histogram in lat/long

# 2. Scales
# x/y
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()
col_sc = bqplot.ColorScale(scheme='RdPu')

# 3. Axis -- x/y AND color
x_ax = bqplot.Axis(scale=x_sc, label='Longitude')
y_ax = bqplot.Axis(scale=y_sc, label='Latitude', orientation='vertical')
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')

# 4. Marks
heat_map = bqplot.GridHeatMap(color=hist2d, row=lat_centers, column=long_centers, 
                             scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'}, # select on click
                             anchor_style={'fill':'blue'}, # fill selection with blue
                             selected_style={'opacity':1.0}, # opaque on selection
                             unselected_style={'opacity':0.8}) # see-through for non-selected

# 5. Interations -- first adding a label
mySelectedLabel = ipywidgets.Label()
# 5.1 on selection function
# def on_selection(change):
#     #print(change)
#     #print(change['owner'])
#     #print(change['owner'].selected)
#     if len(change['owner'].selected) == 1: # allowing only 1 selection
#         i,j = change['owner'].selected[0]
#         v = hist2d[i,j] # grab data value
#         mySelectedLabel.value = 'Total duration in sum(log(sec))=' + str(v) # set label
        
# 5.2 linking of the heatmap traits with this function
#heat_map.observe(on_selection,'selected')

# Put it together as a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, y_ax, x_ax])
#fig
#myDashboard = ipywidgets.VBox([mySelectedLabel, fig])
#myDashboard

In [71]:
### (II) SCATTER PLOT

# 2. Scales -- date-time scale
x_scl = bqplot.DateScale(min=dt.datetime(1950,1,1), max=dt.datetime(2021,1,1)) # formatting for x-scale
y_scl = bqplot.LogScale() # taking log on "viz engine side" not on the data-side this time

# 3. Axis
ax_xcl = bqplot.Axis(label='Date',scale=x_scl)
ax_ycl = bqplot.Axis(label='Duration in Seconds', scale=y_scl, orientation='vertical', side='left')

# 4. Marks
i,j = 19,0 # for-though, I know this bin has data!
longs = [long_edges[j], long_edges[j+1]]
lats = [lat_edges[i], lat_edges[i+1]]
region_mask = ( (ufos['latitude'] >= lats[0]) & (ufos['latitude']<=lats[1]) &\
              (ufos['longitude'] >= longs[0]) & (ufos['longitude']<=longs[1]))
duration_scatter = bqplot.Scatter(x=ufos['date'][region_mask],
                                 y=ufos['duration_seconds'][region_mask],
                                 scales={'x':x_scl, 'y':y_scl})

# All together as duration figure
fig_dur = bqplot.Figure(marks=[duration_scatter], axes=[ax_xcl, ax_ycl])

In [72]:
### (III) LINK THE TWO PLOTS AND LABEL TOGETHER (Step 5 all together)
def on_selection(change):
    if len(change['owner'].selected) == 1: # allowing only 1 selection
        i,j = change['owner'].selected[0]
        v = hist2d[i,j] # grab data value
        mySelectedLabel.value = 'Total duration in sum(log(sec))=' + str(v) # set label
        #### Update the scatter plot ###
        #i,j = 19,0 # for-though, I know this bin has data!
        longs = [long_edges[j], long_edges[j+1]]
        lats = [lat_edges[i], lat_edges[i+1]]
        region_mask = ( (ufos['latitude'] >= lats[0]) & (ufos['latitude']<=lats[1]) &\
                      (ufos['longitude'] >= longs[0]) & (ufos['longitude']<=longs[1]))
        # update the x & y traits of our scatter plot based on the new region mask
        duration_scatter.x = ufos['date'][region_mask]
        duration_scatter.y = ufos['duration_seconds'][region_mask]
        
# 5.2 linking of the heatmap traits with this function
heat_map.observe(on_selection,'selected')

In [73]:
fig.layout.min_width='400px'
fig_dur.layout.min_width ='400px'
figures = ipywidgets.HBox([fig, fig_dur])
myDashboard = ipywidgets.VBox([mySelectedLabel, figures])
myDashboard

Check on the possible keys of our scatter plot to see how to update its *traits*:

In [69]:
duration_scatter.keys 

['_model_module',
 '_model_module_version',
 '_model_name',
 '_view_count',
 '_view_module',
 '_view_module_version',
 '_view_name',
 'apply_clip',
 'color',
 'colors',
 'default_size',
 'default_skew',
 'display_legend',
 'display_names',
 'drag_color',
 'drag_size',
 'enable_delete',
 'enable_hover',
 'enable_move',
 'fill',
 'hovered_point',
 'hovered_style',
 'interactions',
 'label_display_horizontal_offset',
 'label_display_vertical_offset',
 'labels',
 'marker',
 'names',
 'names_unique',
 'opacities',
 'opacity',
 'preserve_domain',
 'restrict_x',
 'restrict_y',
 'rotation',
 'scales',
 'scales_metadata',
 'selected',
 'selected_style',
 'size',
 'skew',
 'stroke',
 'stroke_width',
 'tooltip',
 'tooltip_location',
 'tooltip_style',
 'unhovered_style',
 'unselected_style',
 'update_on_move',
 'visible',
 'x',
 'y']

Trying the 2nd plot again -- a barplot this time!

In [75]:
# 2. Scales
x_scl = bqplot.LinearScale()
y_scl = bqplot.LinearScale()

# 3. Axis
ax_xcl = bqplot.Axis(label='Date', scale=x_scl)
ax_ycl = bqplot.Axis(label='Total Duration in Sec', orientation='vertical', scale=y_scl) # an accumulation in a date bin

In [76]:
# 4. Marks -- need a particular data subset
i,j = 19,0 # for-though, I know this bin has data!
longs = [long_edges[j], long_edges[j+1]]
lats = [lat_edges[i], lat_edges[i+1]]
region_mask = ( (ufos['latitude'] >= lats[0]) & (ufos['latitude']<=lats[1]) &\
                (ufos['longitude'] >= longs[0]) & (ufos['longitude']<=longs[1]))

In [77]:
ufos['date']

0       1949-10-10 20:30:00
1       1949-10-10 21:00:00
2       1955-10-10 17:00:00
3       1956-10-10 21:00:00
4       1960-10-10 20:00:00
                ...        
80327   2013-09-09 21:15:00
80328   2013-09-09 22:00:00
80329   2013-09-09 22:00:00
80330   2013-09-09 22:20:00
80331   2013-09-09 23:00:00
Name: date, Length: 80332, dtype: datetime64[ns]

In [78]:
ufos['date'].dt.year

0        1949
1        1949
2        1955
3        1956
4        1960
         ... 
80327    2013
80328    2013
80329    2013
80330    2013
80331    2013
Name: date, Length: 80332, dtype: int64

In [79]:
ufos['year'] = ufos['date'].dt.year # adding in a year column to our dataset

In [80]:
ufos

date                  city state country     shape  \
0     1949-10-10 20:30:00            san marcos    tx      us  cylinder   
1     1949-10-10 21:00:00          lackland afb    tx     NaN     light   
2     1955-10-10 17:00:00  chester (uk/england)   NaN      gb    circle   
3     1956-10-10 21:00:00                  edna    tx      us    circle   
4     1960-10-10 20:00:00               kaneohe    hi      us     light   
...                   ...                   ...   ...     ...       ...   
80327 2013-09-09 21:15:00             nashville    tn      us     light   
80328 2013-09-09 22:00:00                 boise    id      us    circle   
80329 2013-09-09 22:00:00                  napa    ca      us     other   
80330 2013-09-09 22:20:00                vienna    va      us    circle   
80331 2013-09-09 23:00:00                edmond    ok      us     cigar   

       duration_seconds    duration  \
0                2700.0  45 minutes   
1                7200.0     1-2 hrs   
2                  20.0  20 seconds   
3                  20.0    1/2 hour   
4                 900.0  15 minutes   
...                 ...         ...   
80327             600.0  10 minutes   
80328            1200.0  20 minutes   
80329            1200.0        hour   
80330               5.0   5 seconds   
80331            1020.0  17 minutes   

                                                 comment report_date  \
0      This event took place in early fall around 194...  2004-04-27   
1      1949 Lackland AFB&#44 TX.  Lights racing acros...  2005-12-16   
2      Green/Orange circular disc over Chester&#44 En...  2008-01-21   
3      My older brother and twin sister were leaving ...  2004-01-17   
4      AS a Marine 1st Lt. flying an FJ4B fighter/att...  2004-01-22   
...                                                  ...         ...   
80327  Round from the distance/slowly changing colors...  2013-09-30   
80328  Boise&#44 ID&#44 spherical&#44 20 min&#44 10 r...  2013-09-30   
80329                                       Napa UFO&#44  2013-09-30   
80330  Saw a five gold lit cicular craft moving fastl...  2013-09-30   
80331  2 witnesses 2  miles apart&#44 Red &amp; White...  2013-09-30   

        latitude   longitude  year  
0      29.883056  -97.941111  1949  
1      29.384210  -98.581082  1949  
2      53.200000   -2.916667  1955  
3      28.978333  -96.645833  1956  
4      21.418056 -157.803611  1960  
...          ...         ...   ...  
80327  36.165833  -86.784444  2013  
80328  43.613611 -116.202500  2013  
80329  38.297222 -122.284444  2013  
80330  38.901111  -77.265556  2013  
80331  35.652778  -97.477778  2013  

[80332 rows x 12 columns]

Use NumPy to bin our data over this year column IN OUR CHOSEN SUBSET:

In [83]:
dur, dur_edges = np.histogram(ufos['year'][region_mask], 
                              weights=ufos['duration_seconds'][region_mask], 
                              bins=10)

In [84]:
dur

array([1.26000e+03, 0.00000e+00, 9.00000e+02, 2.70000e+02, 6.00000e+02,
       0.00000e+00, 4.98000e+03, 8.39800e+03, 2.97280e+04, 6.28123e+05])

In [85]:
dur.shape, dur_edges.shape

((10,), (11,))

Use some inline programming to grab bin centers:

In [86]:
dur_centers = (dur_edges[:-1]+dur_edges[1:])/2

In [87]:
dur_centers

array([1952.2, 1958.6, 1965. , 1971.4, 1977.8, 1984.2, 1990.6, 1997. ,
       2003.4, 2009.8])

In [88]:
dur_edges

array([1949. , 1955.4, 1961.8, 1968.2, 1974.6, 1981. , 1987.4, 1993.8,
       2000.2, 2006.6, 2013. ])

In [90]:
# 4. (cont) create the mark -- bar plot
dur_bar = bqplot.Bars(x=dur_centers, y=dur, scales={'x':x_scl, 'y':y_scl})

In [91]:
fig_bar = bqplot.Figure(marks=[dur_bar], axes=[ax_xcl,ax_ycl])

In [92]:
fig_bar

Figure(axes=[Axis(label='Date', scale=LinearScale(), side='bottom'), Axis(label='Total Duration in Sec', orien…

In [125]:
### (I) GRID HEAT MAP
# 1. Data -- 2d histogram in lat/long

# 2. Scales
# x/y
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()
col_sc = bqplot.ColorScale(scheme='RdPu')

# 3. Axis -- x/y AND color
x_ax = bqplot.Axis(scale=x_sc, label='Longitude')
y_ax = bqplot.Axis(scale=y_sc, label='Latitude', orientation='vertical')
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')

# 4. Marks
heat_map = bqplot.GridHeatMap(color=hist2d, row=lat_centers, column=long_centers, 
                             scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'}, # select on click
                             anchor_style={'fill':'blue'}, # fill selection with blue
                             selected_style={'opacity':1.0}, # opaque on selection
                             unselected_style={'opacity':0.8}) # see-through for non-selected

# 5. Interations -- first adding a label
mySelectedLabel = ipywidgets.Label()
# # 5.1 on selection function
# def on_selection(change):
#     #print(change)
#     #print(change['owner'])
#     #print(change['owner'].selected)
#     if len(change['owner'].selected) == 1: # allowing only 1 selection
#         i,j = change['owner'].selected[0]
#         v = hist2d[i,j] # grab data value
#         mySelectedLabel.value = 'Total duration in sum(log(sec))=' + str(v) # set label
        
# # 5.2 linking of the heatmap traits with this function
# heat_map.observe(on_selection,'selected')

# Put it together as a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, y_ax, x_ax])

In [126]:
### (II) BAR PLOT
# 2. Scales
x_scl = bqplot.LinearScale()
y_scl = bqplot.LinearScale()

# 3. Axis
ax_xcl = bqplot.Axis(label='Date', scale=x_scl)
ax_ycl = bqplot.Axis(label='Total Duration in Sec', 
                     orientation='vertical', scale=y_scl) # an accumulation in a date bin

# 4. Marks -- need a particular data subset
i,j = 19,0 # for-though, I know this bin has data!
longs = [long_edges[j], long_edges[j+1]]
lats = [lat_edges[i], lat_edges[i+1]]
region_mask = ( (ufos['latitude'] >= lats[0]) & (ufos['latitude']<=lats[1]) &
               (ufos['longitude'] >= longs[0]) & (ufos['longitude']<=longs[1]))

# This assumes we have added this column somewhere with:
#ufos['year'] = ufos['date'].dt.year # adding in a year column to our dataset

# for reference:
#x_scl = bqplot.DateScale(min=dt.datetime(1950,1,1), max=dt.datetime(2021,1,1)) # formatting for x-scale
dur, dur_edges = np.histogram(ufos['year'][region_mask], 
                              weights=ufos['duration_seconds'][region_mask], 
                              bins=[1940, 1960, 1980, 2000,  2020])

dur_centers = (dur_edges[:-1]+dur_edges[1:])/2

# 4. (cont) create the mark -- bar plot
dur_bar = bqplot.Bars(x=dur_centers, y=dur, scales={'x':x_scl, 'y':y_scl})

# All together as a figure
fig_bar = bqplot.Figure(marks=[dur_bar], axes=[ax_xcl,ax_ycl])

In [127]:
### (III) LINKING BARPLOT TO GRIDHEATMAP

# 5.1 on selection function
def on_selection(change):
    if len(change['owner'].selected) == 1: # allowing only 1 selection
        i,j = change['owner'].selected[0]
        v = hist2d[i,j] # grab data value
        mySelectedLabel.value = 'Total duration in sum(log(sec))=' + str(v) # set label
        ### BARPLOT GETS UPDATED
        #i,j = 19,0 # for-though, I know this bin has data!
        longs = [long_edges[j], long_edges[j+1]]
        lats = [lat_edges[i], lat_edges[i+1]]
        region_mask = ( (ufos['latitude'] >= lats[0]) & (ufos['latitude']<=lats[1]) &\
                        (ufos['longitude'] >= longs[0]) & (ufos['longitude']<=longs[1]))

        dur, dur_edges = np.histogram(ufos['year'][region_mask], 
                                      weights=ufos['duration_seconds'][region_mask], 
                                      bins=[1940, 1960, 1980, 2000,  2020])

        dur_centers = (dur_edges[:-1]+dur_edges[1:])/2
        dur_bar.x = dur_centers
        dur_bar.y = dur

        
# 5.2 linking of the heatmap traits with this function
heat_map.observe(on_selection,'selected')


In [128]:
## Putting together into a dashboard
fig.layout.min_width='500px'
fig_bar.layout.min_width='500px'
figures = ipywidgets.HBox([fig, fig_bar])

myDashboard = ipywidgets.VBox([mySelectedLabel, figures])
myDashboard

In [99]:
# what traits can we update in our barplot mark?
dur_bar.keys

['_model_module',
 '_model_module_version',
 '_model_name',
 '_view_count',
 '_view_module',
 '_view_module_version',
 '_view_name',
 'align',
 'apply_clip',
 'base',
 'color',
 'color_mode',
 'colors',
 'display_legend',
 'enable_hover',
 'fill',
 'interactions',
 'label_display',
 'label_display_format',
 'label_display_horizontal_offset',
 'label_display_vertical_offset',
 'label_font_style',
 'labels',
 'opacities',
 'opacity_mode',
 'orientation',
 'padding',
 'preserve_domain',
 'scales',
 'scales_metadata',
 'selected',
 'selected_style',
 'stroke',
 'stroke_width',
 'tooltip',
 'tooltip_location',
 'tooltip_style',
 'type',
 'unselected_style',
 'visible',
 'x',
 'y']

# Looking forward to next week -- bqplot maps

In [111]:
map_mark = bqplot.Map(scales={'projection':bqplot.AlbersUSA()})
fig = bqplot.Figure(marks=[map_mark], title='Basic Map Example')
fig

Figure(fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, marks=[Map(hovered_styles={'hovered_fill…

Breaking it down a little further:

In [112]:
# map data
state_data = bqplot.topo_load('map_data/USStatesMap.json')

# scales
sc_geo = bqplot.AlbersUSA()

# marks
states_map = bqplot.Map(map_data=state_data, scales={'projection':sc_geo})

# all together as a figure
fig = bqplot.Figure(marks=[states_map], title='US States Map Example',
                   fig_margin={'top':0, 'bottom':0, 'left':0, 'right':0}) # zooming in
fig

Figure(fig_margin={'top': 0, 'bottom': 0, 'left': 0, 'right': 0}, marks=[Map(hovered_styles={'hovered_fill': '…

In [114]:
# map data
geo_data = bqplot.topo_load('map_data/WorldMap.json')

# scales
sc_geo = bqplot.Mercator()

# marks
geo_map = bqplot.Map(map_data=geo_data, scales={'projection':sc_geo})

# all together as a figure
fig = bqplot.Figure(marks=[geo_map], title='Map Example',
                   fig_margin={'top':0, 'bottom':0, 'left':0, 'right':0}) # zooming in
fig

Figure(fig_margin={'top': 0, 'bottom': 0, 'left': 0, 'right': 0}, marks=[Map(hovered_styles={'hovered_fill': '…

In [115]:
# map data
geo_data = bqplot.topo_load('map_data/WorldMap.json')

# scales
sc_geo = bqplot.Gnomonic()

# marks
geo_map = bqplot.Map(map_data=geo_data, scales={'projection':sc_geo})

# all together as a figure
fig = bqplot.Figure(marks=[geo_map], title='Map Example',
                   fig_margin={'top':0, 'bottom':0, 'left':0, 'right':0}) # zooming in
fig

Figure(fig_margin={'top': 0, 'bottom': 0, 'left': 0, 'right': 0}, marks=[Map(hovered_styles={'hovered_fill': '…

In [117]:
# map data
geo_data = bqplot.topo_load('map_data/WorldMap.json')

# scales
sc_geo = bqplot.Stereographic()

# marks
geo_map = bqplot.Map(map_data=geo_data, scales={'projection':sc_geo})

# all together as a figure
fig = bqplot.Figure(marks=[geo_map], title='Map Example',
                   fig_margin={'top':0, 'bottom':0, 'left':0, 'right':0}) # zooming in
fig

Figure(fig_margin={'top': 0, 'bottom': 0, 'left': 0, 'right': 0}, marks=[Map(hovered_styles={'hovered_fill': '…

In [118]:
region_mask

0        False
1        False
2        False
3        False
4        False
         ...  
80327    False
80328    False
80329    False
80330    False
80331    False
Length: 80332, dtype: bool

In [119]:
ufos.loc[region_mask]

date        city state country    shape  \
327   2001-10-11 02:15:00   fairbanks    ak      us    other   
2845  2012-10-18 21:30:00   fairbanks    ak      us    light   
3620  2000-10-02 23:00:00   fairbanks    ak      us      NaN   
4602  2012-10-25 23:00:00  north pole    ak      us    light   
6011  2013-10-31 20:30:00   fairbanks    ak      us  diamond   
...                   ...         ...   ...     ...      ...   
77347 1998-09-24 22:35:00  north pole    ak      us   sphere   
77497 2013-09-24 20:35:00   fairbanks    ak      us   circle   
78571 2013-09-29 21:30:00   fairbanks    ak      us    light   
79029 2012-09-03 21:57:00   fairbanks    ak      us  unknown   
79470 2013-09-05 22:00:00   fairbanks    ak      us     disk   

       duration_seconds      duration  \
327              1800.0    30 minutes   
2845              600.0  5-10 minutes   
3620              300.0          hour   
4602               15.0    15 seconds   
6011              180.0     3 minutes   
...                 ...           ...   
77347             600.0    10 minutes   
77497             120.0    ~2 minutes   
78571             420.0   5-7 minutes   
79029             120.0     2 minutes   
79470             300.0     5 minutes   

                                                 comment report_date  \
327    It looked like a star but it would move and af...  2001-10-12   
2845   Changing light from bright to dim&#44 to off t...  2012-10-30   
3620   Lights gradually coming on&#44 and then going ...  2002-12-23   
4602   It was late at night and me and my mother were...  2012-12-20   
6011          UFO seen over civilian side of Birch Hill.  2013-11-11   
...                                                  ...         ...   
77347  Two Orange sphere appeared low on horizon just...  1998-09-26   
77497                 3 white orbs. 2 in front 1 behind.  2013-09-30   
78571           2 orange orbs fly south over chena ridge  2013-09-30   
79029  Metallic sounds and bright flash of light - Se...  2012-09-24   
79470             HUGE SAUCER FLYING INTO FORT WAINRIGHT  2013-09-30   

        latitude   longitude  year  
327    64.837778 -147.716389  2001  
2845   64.837778 -147.716389  2012  
3620   64.837778 -147.716389  2000  
4602   64.751111 -147.349444  2012  
6011   64.837778 -147.716389  2013  
...          ...         ...   ...  
77347  64.751111 -147.349444  1998  
77497  64.837778 -147.716389  2013  
78571  64.837778 -147.716389  2013  
79029  64.837778 -147.716389  2012  
79470  64.837778 -147.716389  2013  

[74 rows x 12 columns]