# In Class Notebook, Week 06

You can always paste the URL of this notebook (https://github.com/UIUC-iSchool-DataViz/is445_AOUAOG_fall2021/blob/master/week06/inClass_week06.ipynb ) into the nbviewer interface for a plain-text rendering:

https://kokes.github.io/nbviewer.js/viewer.html

In [1]:
# importing our usual things:
import numpy as np
import ipywidgets
import bqplot # new thing!

In [2]:
# 1. Data
x = np.arange(100)

In [6]:
#x

In [4]:
y = np.random.random(100) # random numbers your's might be different!

In [7]:
#y

In [8]:
# 2. Scales -- how will data translate to Marks
bqplot.LinearScale?

In [9]:
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

In [10]:
x_sc

LinearScale()

In [11]:
# 3. Marks -- how we draw the data, here I'm going to make a line plot, so I'll use a line mark
bqplot.Lines?

In [12]:
lines = bqplot.Lines(x=x,y=y, scales={'x':x_sc, 'y':y_sc})

In [14]:
#lines

In [15]:
# 4. Axis
bqplot.Axis?

In [16]:
ax_x = bqplot.Axis(scale=x_sc, label='X Value')
ax_y = bqplot.Axis(scale=y_sc, label='Y Value', orientation='vertical')

In [17]:
# 5. Around here there could be interactions defined, but not yet!

In [18]:
# 6. Finally put it all together as a figure
fig = bqplot.Figure(marks=[lines], axes=[ax_x,ax_y])

In [19]:
fig # note here: display(fig) from IPython.display like in test homework 1 (if you have no image)

Figure(axes=[Axis(label='X Value', scale=LinearScale(), side='bottom'), Axis(label='Y Value', orientation='ver…

In [20]:
bqplot.interacts.PanZoom?

In [21]:
pz = bqplot.interacts.PanZoom(scales={'x':[x_sc], 'y':[y_sc]})

In [22]:
pz

PanZoom(scales={'x': [LinearScale()], 'y': [LinearScale()]})

In [23]:
fig = bqplot.Figure(marks=[lines], axes=[ax_x,ax_y], interaction=pz)
fig

Figure(axes=[Axis(label='X Value', scale=LinearScale(), side='bottom'), Axis(label='Y Value', orientation='ver…

Another example using random data:

In [27]:
# 1. Data
x = np.random.random(100)
y = np.random.random(100)

In [28]:
# 2. scales
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

In [29]:
# 3. marks
bqplot.Scatter?

In [30]:
scatters = bqplot.Scatter(x=x,y=y, scales={'x':x_sc, 'y':y_sc})

In [31]:
# 4. Axis
x_ax = bqplot.Axis(scale=x_sc, label='X')
y_ax = bqplot.Axis(scale=y_sc, label='Y', orientation='vertical')

In [32]:
# 5. interactions around here -- FastIntervalSelector
selector = bqplot.interacts.FastIntervalSelector(scale=x_sc, marks=[scatters])

In [34]:
# 6. Make the figure
fig = bqplot.Figure(marks=[scatters], axes=[x_ax, y_ax], interaction = selector)
fig

Figure(axes=[Axis(label='X', scale=LinearScale(), side='bottom'), Axis(label='Y', orientation='vertical', scal…

In [35]:
selector.keys

['_model_module',
 '_model_module_version',
 '_model_name',
 '_view_count',
 '_view_module',
 '_view_module_version',
 '_view_name',
 'color',
 'marks',
 'scale',
 'selected',
 'size']

In [37]:
selector.selected

array([0.21758859, 0.40739032])

In [38]:
scatters.keys

['_model_module',
 '_model_module_version',
 '_model_name',
 '_view_count',
 '_view_module',
 '_view_module_version',
 '_view_name',
 'apply_clip',
 'color',
 'colors',
 'default_size',
 'default_skew',
 'display_legend',
 'display_names',
 'drag_color',
 'drag_size',
 'enable_delete',
 'enable_hover',
 'enable_move',
 'fill',
 'hovered_point',
 'hovered_style',
 'interactions',
 'label_display_horizontal_offset',
 'label_display_vertical_offset',
 'labels',
 'marker',
 'names',
 'names_unique',
 'opacities',
 'opacity',
 'preserve_domain',
 'restrict_x',
 'restrict_y',
 'rotation',
 'scales',
 'scales_metadata',
 'selected',
 'selected_style',
 'size',
 'skew',
 'stroke',
 'stroke_width',
 'tooltip',
 'tooltip_location',
 'tooltip_style',
 'unhovered_style',
 'unselected_style',
 'update_on_move',
 'visible',
 'x',
 'y']

In [39]:
scatters.unselected_style={'opacity':0.5} # a little see-through for unselected points

In [40]:
scatters.selected_style = {'fill':'red', 'stroke':'yellow'}

In [41]:
fig

Figure(axes=[Axis(label='X', scale=LinearScale(), side='bottom'), Axis(label='Y', orientation='vertical', scal…

## Random data in 2D

In [42]:
# 1. data
data = np.random.random((10,10))

In [44]:
data.shape

(10, 10)

In [59]:
bqplot.GridHeatMap?

In [48]:
# 2. Scales
col_sc = bqplot.ColorScale() # like x/y scale, but in "color space"

# 3. Marks
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc})

# 4. Axis 
# rows/columns, skipping for now
# color bars

# 5. Interactions, skipping as well

# 6. Figure object
fig = bqplot.Figure(marks=[heat_map])
fig

Figure(fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, marks=[GridHeatMap(color=array([[0.89691…

In [52]:
# 1. Data -- same as above

# 2. Scales
col_sc = bqplot.ColorScale(scheme = 'Reds') # like x/y scale, but in "color space"

# 3. Marks
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc})

# 4. Axis 
# rows/columns, skipping for now
# color bars

# 5. Interactions, skipping as well

# 6. Figure object
fig = bqplot.Figure(marks=[heat_map])
fig

Figure(fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, marks=[GridHeatMap(color=array([[0.89691…

In [54]:
# 1. Data -- same as above

# 2. Scales
col_sc = bqplot.ColorScale(scheme = 'Reds') # like x/y scale, but in "color space"

# 3. Marks
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc})

# 4. Axis 
c_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')

# 5. Interactions, skipping as well

# 6. Figure object
fig = bqplot.Figure(marks=[heat_map], axes=[c_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right')], fig_margin={'t…

In [58]:
# 1. Data -- same as above

# 2. Scales
col_sc = bqplot.ColorScale(scheme = 'Reds') # like x/y scale, but in "color space"
x_sc = bqplot.OrdinalScale() # ordered, categorical data, because our bins are more like categorical bins
y_sc = bqplot.OrdinalScale()

# 3. Marks
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 'row':y_sc, 'column':x_sc})
# note: we can pass arrays/lists of names for each categorical column, here we are just
#. passing the scales

# 4. Axis 
c_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 5. Interactions, skipping as well

# 6. Figure object
fig = bqplot.Figure(marks=[heat_map], axes=[c_ax, x_ax, y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right'), Axis(scale=Ordi…

In [60]:
heat_map.keys

['_model_module',
 '_model_module_version',
 '_model_name',
 '_view_count',
 '_view_module',
 '_view_module_version',
 '_view_name',
 'anchor_style',
 'apply_clip',
 'color',
 'column',
 'column_align',
 'display_format',
 'display_legend',
 'enable_hover',
 'font_style',
 'interactions',
 'labels',
 'null_color',
 'opacity',
 'preserve_domain',
 'row',
 'row_align',
 'scales',
 'scales_metadata',
 'selected',
 'selected_style',
 'stroke',
 'tooltip',
 'tooltip_location',
 'tooltip_style',
 'unselected_style',
 'visible']

In [63]:
# 1. Data -- same as above

# 2. Scales
col_sc = bqplot.ColorScale(scheme = 'Reds') # like x/y scale, but in "color space"
x_sc = bqplot.OrdinalScale() # ordered, categorical data, because our bins are more like categorical bins
y_sc = bqplot.OrdinalScale()

# 3. Marks
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'opacity':1.0}, 
                             unselected_style={'opacity':0.8}, 
                             anchor_style={'fill':'blue'})
# note: we can pass arrays/lists of names for each categorical column, here we are just
#. passing the scales

# 4. Axis 
c_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 5. Interactions, skipping as well

# 6. Figure object
fig = bqplot.Figure(marks=[heat_map], axes=[c_ax, x_ax, y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right'), Axis(scale=Ordi…

In [64]:
# 1. Data -- same as above

# 2. Scales
col_sc = bqplot.ColorScale(scheme = 'Reds') # like x/y scale, but in "color space"
x_sc = bqplot.OrdinalScale() # ordered, categorical data, because our bins are more like categorical bins
y_sc = bqplot.OrdinalScale()

# 3. Marks
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             anchor_style={'fill':'blue'})
# note: we can pass arrays/lists of names for each categorical column, here we are just
#. passing the scales

# 4. Axis 
c_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 5. Interactions, skipping as well

# 6. Figure object
fig = bqplot.Figure(marks=[heat_map], axes=[c_ax, x_ax, y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right'), Axis(scale=Ordi…

In [66]:
heat_map.selected

array([[4, 4]])

In [68]:
mySelectedLabel = ipywidgets.Label() # update what the value of the data in our selected bin is

In [69]:
def on_selected(change): # take a look at what changes when I select a new bin
    print(change)

In [70]:
# 1. Data -- same as above

# 2. Scales
col_sc = bqplot.ColorScale(scheme = 'Reds') # like x/y scale, but in "color space"
x_sc = bqplot.OrdinalScale() # ordered, categorical data, because our bins are more like categorical bins
y_sc = bqplot.OrdinalScale()

# 3. Marks
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             anchor_style={'fill':'blue'})
# note: we can pass arrays/lists of names for each categorical column, here we are just
#. passing the scales

# 4. Axis 
c_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 5. Interactions
heat_map.observe(on_selected,'selected')

# 6. Figure object
fig = bqplot.Figure(marks=[heat_map], axes=[c_ax, x_ax, y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right'), Axis(scale=Ordi…

{'name': 'selected', 'old': None, 'new': array([[3, 6]]), 'owner': GridHeatMap(anchor_style={'fill': 'blue'}, color=array([[0.89691181, 0.48859829, 0.95006818, 0.69601777, 0.73775513,
        0.38569269, 0.68017469, 0.54575597, 0.00480574, 0.24579393],
       [0.7962746 , 0.1783357 , 0.94882097, 0.40581645, 0.52912763,
        0.37285539, 0.82120449, 0.94371314, 0.68962898, 0.91471067],
       [0.4698892 , 0.99621421, 0.9176743 , 0.48230689, 0.84884311,
        0.2255048 , 0.75520046, 0.50655736, 0.10780837, 0.90871802],
       [0.68627458, 0.45620166, 0.99696782, 0.80687665, 0.30225841,
        0.15660133, 0.28941562, 0.18002238, 0.39746809, 0.47033515],
       [0.55108775, 0.65433285, 0.29482268, 0.07033723, 0.91848317,
        0.96783228, 0.78990487, 0.47010381, 0.81955856, 0.32139952],
       [0.06993581, 0.05198585, 0.32260134, 0.12551586, 0.61415097,
        0.08934409, 0.83918262, 0.20375412, 0.69105229, 0.15136115],
       [0.64619925, 0.74768848, 0.34259561, 0.20438315, 0.9154

In [71]:
# 1. Data -- same as above

# 2. Scales
col_sc = bqplot.ColorScale(scheme = 'Reds') # like x/y scale, but in "color space"
x_sc = bqplot.OrdinalScale() # ordered, categorical data, because our bins are more like categorical bins
y_sc = bqplot.OrdinalScale()

# 3. Marks
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             anchor_style={'fill':'blue'})
# note: we can pass arrays/lists of names for each categorical column, here we are just
#. passing the scales

# 4. Axis 
c_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 5. Interactions
def on_selected(change): # take a look at what changes when I select a new bin
    print(change['owner'].selected)
heat_map.observe(on_selected,'selected')

# 6. Figure object
fig = bqplot.Figure(marks=[heat_map], axes=[c_ax, x_ax, y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right'), Axis(scale=Ordi…

[[9 2]]
[[4 2]]
[[3 3]]
[[3 4]]
[[4 4]]
[[2 4]]
[[9 4]]
[[0 4]]
[[0 4]
 [0 5]]
[[0 4]
 [0 5]
 [1 5]]
[[0 4]
 [0 5]
 [1 5]
 [2 5]]


In [72]:
# 1. Data -- same as above

# 2. Scales
col_sc = bqplot.ColorScale(scheme = 'Reds') # like x/y scale, but in "color space"
x_sc = bqplot.OrdinalScale() # ordered, categorical data, because our bins are more like categorical bins
y_sc = bqplot.OrdinalScale()

# 3. Marks
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             anchor_style={'fill':'blue'})
# note: we can pass arrays/lists of names for each categorical column, here we are just
#. passing the scales

# 4. Axis 
c_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 5. Interactions
def on_selected(change): # take a look at what changes when I select a new bin
    if len(change['owner'].selected) == 1: # checking that user is only selecting one element
        print(change['owner'].selected[0]) # printing that single element
    
heat_map.observe(on_selected,'selected')

# 6. Figure object
fig = bqplot.Figure(marks=[heat_map], axes=[c_ax, x_ax, y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right'), Axis(scale=Ordi…

[0 2]
[0 3]
[3 4]
[2 5]
[4 5]
[5 5]
[5 2]


In [73]:
# 1. Data -- same as above

# 2. Scales
col_sc = bqplot.ColorScale(scheme = 'Reds') # like x/y scale, but in "color space"
x_sc = bqplot.OrdinalScale() # ordered, categorical data, because our bins are more like categorical bins
y_sc = bqplot.OrdinalScale()

# 3. Marks
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             anchor_style={'fill':'blue'})
# note: we can pass arrays/lists of names for each categorical column, here we are just
#. passing the scales

# 4. Axis 
c_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 5. Interactions
def on_selected(change): # take a look at what changes when I select a new bin
    if len(change['owner'].selected) == 1: # checking that user is only selecting one element
        print(change['owner'].selected[0]) # printing that single element
        i,j = change['owner'].selected[0]
        val = data[i,j]
        print('value=',val)
    
heat_map.observe(on_selected,'selected')

# 6. Figure object
fig = bqplot.Figure(marks=[heat_map], axes=[c_ax, x_ax, y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right'), Axis(scale=Ordi…

[0 0]
value= 0.896911809463098
[0 8]
value= 0.004805737740776195
[6 9]
value= 0.9750591100354541
[3 6]
value= 0.2894156198658885


In [77]:
mySelectedLabel.value = 'Hello!'

In [76]:
mySelectedLabel

Label(value='Hi there')

In [78]:
# 1. Data -- same as above

# 2. Scales
col_sc = bqplot.ColorScale(scheme = 'Reds') # like x/y scale, but in "color space"
x_sc = bqplot.OrdinalScale() # ordered, categorical data, because our bins are more like categorical bins
y_sc = bqplot.OrdinalScale()

# 3. Marks
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             anchor_style={'fill':'blue'})
# note: we can pass arrays/lists of names for each categorical column, here we are just
#. passing the scales

# 4. Axis 
c_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 5. Interactions
def on_selected(change): # take a look at what changes when I select a new bin
    if len(change['owner'].selected) == 1: # checking that user is only selecting one element
        #print(change['owner'].selected[0]) # printing that single element
        i,j = change['owner'].selected[0]
        val = data[i,j]
        #print('value=',val)
        mySelectedLabel.value = 'Data Value='+str(val)
        
heat_map.observe(on_selected,'selected')

# 6. Figure object
fig = bqplot.Figure(marks=[heat_map], axes=[c_ax, x_ax, y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right'), Axis(scale=Ordi…

In [79]:
mySelectedLabel

Label(value='Data Value=0.9969678213227691')

In [80]:
# 1. Data -- same as above

# 2. Scales
col_sc = bqplot.ColorScale(scheme = 'Reds') # like x/y scale, but in "color space"
x_sc = bqplot.OrdinalScale() # ordered, categorical data, because our bins are more like categorical bins
y_sc = bqplot.OrdinalScale()

# 3. Marks
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             anchor_style={'fill':'blue'})
# note: we can pass arrays/lists of names for each categorical column, here we are just
#. passing the scales

# 4. Axis 
c_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 5. Interactions
def on_selected(change): # take a look at what changes when I select a new bin
    if len(change['owner'].selected) == 1: # checking that user is only selecting one element
        #print(change['owner'].selected[0]) # printing that single element
        i,j = change['owner'].selected[0]
        val = data[i,j]
        #print('value=',val)
        mySelectedLabel.value = 'Data Value='+str(val)
        
heat_map.observe(on_selected,'selected')

# 6. Figure object
fig = bqplot.Figure(marks=[heat_map], axes=[c_ax, x_ax, y_ax])
#fig
myDashboard = ipywidgets.VBox([mySelectedLabel, fig])
myDashboard

In [82]:
data.shape

(10, 10)

## Random 3D data

In [83]:
data = np.random.random((10,10,20))

In [85]:
data.shape

(10, 10, 20)

In [86]:
data[0,0,:]

array([0.17876132, 0.61754544, 0.40777043, 0.88176259, 0.0496922 ,
       0.78890102, 0.45295427, 0.41170028, 0.5144766 , 0.34964404,
       0.0486498 , 0.56107582, 0.89939653, 0.48313486, 0.48337734,
       0.21999646, 0.59561444, 0.43669691, 0.63594383, 0.96145115])

In [88]:
np.sum(data,axis=2).shape

(10, 10)

In [89]:
np.sum(data)

1004.6403490676723

In [91]:
np.sum(data,axis=1).shape

(10, 20)

In [92]:
np.sum(data,axis=2)

array([[ 9.97854532,  9.97504454,  8.98695704, 11.07464205, 11.71984928,
        10.28800028, 10.4740139 , 11.22934712,  8.92947199, 10.22342584],
       [10.70365833, 10.68356055, 11.21772251,  7.2260998 , 11.20084407,
        10.07532615, 10.53850024, 11.49114257,  8.26512607,  9.83750006],
       [ 9.00180064,  8.01604974, 11.02335081,  8.53004802, 11.96696634,
        10.06327106,  9.15253536, 12.96474829,  9.19271136, 10.10569155],
       [ 9.9397673 ,  8.97263057, 10.04611252,  9.19364394,  8.68700172,
        10.77571339,  9.16408173,  8.82407512, 10.88200848, 11.12731525],
       [ 9.92417217, 12.09428366,  8.48905911,  8.95086985, 10.95422731,
         9.45691346,  9.5807276 ,  9.32820223,  9.45844396, 10.39959045],
       [ 9.7838676 ,  9.79623417, 10.93620716,  9.87350484, 10.70182509,
         9.25873239,  8.80050868,  8.99686472, 10.71482812,  9.60464047],
       [10.19973589, 10.89797102,  9.6632507 ,  9.5992491 , 10.36458174,
        11.83623664,  8.02120325,  8.30918935

In [93]:
# 1. Data -- same as above

# 2. Scales
col_sc = bqplot.ColorScale(scheme = 'Reds') # like x/y scale, but in "color space"
x_sc = bqplot.OrdinalScale() # ordered, categorical data, because our bins are more like categorical bins
y_sc = bqplot.OrdinalScale()

# 3. Marks
heat_map = bqplot.GridHeatMap(color=np.sum(data,axis=2), 
                              scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             anchor_style={'fill':'blue'})
# note: we can pass arrays/lists of names for each categorical column, here we are just
#. passing the scales

# 4. Axis 
c_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# # 5. Interactions
# def on_selected(change): # take a look at what changes when I select a new bin
#     if len(change['owner'].selected) == 1: # checking that user is only selecting one element
#         #print(change['owner'].selected[0]) # printing that single element
#         i,j = change['owner'].selected[0]
#         val = data[i,j]
#         #print('value=',val)
#         mySelectedLabel.value = 'Data Value='+str(val)
        
# heat_map.observe(on_selected,'selected')

# 6. Figure object
fig = bqplot.Figure(marks=[heat_map], axes=[c_ax, x_ax, y_ax])
#fig
myDashboard = ipywidgets.VBox([mySelectedLabel, fig])
myDashboard