# In Class Notebook, Week 06

You can always paste the URL of this notebook (https://github.com/UIUC-iSchool-DataViz/is445_spring2022/blob/master/week06/inClass_week06.ipynb ) into the nbviewer interface for a plain-text rendering:

https://kokes.github.io/nbviewer.js/viewer.html

In [1]:
import bqplot
import numpy as np
import ipywidgets

In [2]:
# #1 in GoG (Grammar of Graphics) is the data!
x = np.arange(100)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [3]:
y = np.random.random(100)
y

array([0.74834301, 0.12034855, 0.61114136, 0.39294883, 0.03662979,
       0.22368963, 0.97037616, 0.61499508, 0.32417564, 0.81313179,
       0.18968267, 0.59096305, 0.55551813, 0.51394554, 0.00102795,
       0.08458884, 0.62087629, 0.41249747, 0.0605261 , 0.95480678,
       0.27538721, 0.33129882, 0.70467139, 0.12697277, 0.87841244,
       0.06339405, 0.14793161, 0.03824327, 0.36352111, 0.38953838,
       0.80548825, 0.28345535, 0.31704475, 0.76036026, 0.87913638,
       0.0013208 , 0.39163861, 0.27976268, 0.12753653, 0.74749476,
       0.26626977, 0.04927151, 0.90757209, 0.45213034, 0.66324023,
       0.91703347, 0.66232932, 0.22928813, 0.89160544, 0.84123687,
       0.44143626, 0.5647203 , 0.35192449, 0.52572725, 0.34442051,
       0.79082822, 0.06833873, 0.69793728, 0.56151945, 0.33400306,
       0.52154899, 0.99312135, 0.45379439, 0.7846463 , 0.88974152,
       0.17845129, 0.6638428 , 0.06349036, 0.65988712, 0.81578915,
       0.58106948, 0.15215742, 0.03565336, 0.99005736, 0.50871

In [4]:
bqplot.LinearScale?

In [5]:
#2 Scales -- our data is linear so let's use linear scales
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

In [6]:
# #3 Marks -- x/y are linearly related, line is probably a good choice -- Line Mark
bqplot.Lines?

In [7]:
lines = bqplot.Lines(x=x, y=y, scales={'x':x_sc, 'y':y_sc})

In [8]:
# #4 Axis -- where to plot? 
bqplot.Axis?

In [9]:
ax_x = bqplot.Axis(scale=x_sc, label='X')
ax_y = bqplot.Axis(scale=y_sc, label='Y', orientation='vertical')

In [10]:
# #5 is put together as a figure
bqplot.Figure?

In [11]:
fig = bqplot.Figure(marks=[lines], axes=[ax_x,ax_y])

In [12]:
fig

Figure(axes=[Axis(label='X', scale=LinearScale(), side='bottom'), Axis(label='Y', orientation='vertical', scal…

In [13]:
bqplot.interacts?

In [14]:
# let's add a pan-zoom interaction
pz = bqplot.interacts.PanZoom(scales={'x':[x_sc], 'y':[y_sc]})

In [15]:
fig = bqplot.Figure(marks=[lines], axes=[ax_x, ax_y], interaction=pz)

In [16]:
fig

Figure(axes=[Axis(label='X', scale=LinearScale(), side='bottom'), Axis(label='Y', orientation='vertical', scal…

So far, pretty neat, but could could be neater!

### Another example: scatter plot with random data

In [17]:
# 1. Data
x = np.random.random(100)
y = np.random.random(100)

In [19]:
#x,y

In [20]:
# 2. scales
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

# 3. axis (sometimes this can be #4 if we aren't sure what mark to use!)
x_ax = bqplot.Axis(scale=x_sc, label='X')
y_ax = bqplot.Axis(scale=y_sc, label='Y', orientation='vertical')

In [21]:
bqplot.Scatter?

In [22]:
# 4. marks
scatters = bqplot.Scatter(x=x, y=y, scales={'x':x_sc, 'y':y_sc})

In [23]:
# 5. think about interactions (around step 5)
bqplot.interacts.FastIntervalSelector?

In [24]:
selector = bqplot.interacts.FastIntervalSelector(scale=x_sc, marks=[scatters])

In [25]:
# Finally -- together as a fig!
fig = bqplot.Figure(marks=[scatters], axes=[x_ax,y_ax], interaction=selector)
fig

Figure(axes=[Axis(label='X', scale=LinearScale(), side='bottom'), Axis(label='Y', orientation='vertical', scal…

In [26]:
selector.selected

array([0.44144185, 0.77678304])

In [27]:
scatters.unselected_style={'opacity':0.8} #make unselected a bit see-through
scatters.selected_style ={'fill':'red', 'stroke':'yellow'}
# fill selected with red and outline with yellow

## Thinking to higher dimensions (dashboards) -- Random Heatmap in 2D

In [28]:
data = np.random.random((10,10)) # #1 data!

In [30]:
#data

In [31]:
bqplot.GridHeatMap?

In [32]:
bqplot.ColorScale?

In [33]:
# 2 -- scales (just off with only color)
col_sc = bqplot.ColorScale()

# 3. axis (leave off for now)

# 4. Mark -- heatmap using our colors to map to our data
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc})

# 5. skipping interactions

# finally: figure
fig = bqplot.Figure(marks=[heat_map])
fig

Figure(fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, marks=[GridHeatMap(color=array([[0.88300…

In [34]:
bqplot.ColorScale?

In [36]:
# 2 -- scales (just off with only color)
col_sc = bqplot.ColorScale(scheme='Greens')

# 3. axis (leave off for now)

# 4. Mark -- heatmap using our colors to map to our data
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc})

# 5. skipping interactions

# finally: figure
fig = bqplot.Figure(marks=[heat_map])
fig

Figure(fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, marks=[GridHeatMap(color=array([[0.88300…

In [37]:
bqplot.ColorAxis?

In [40]:
# 2 -- scales (just off with only color)
col_sc = bqplot.ColorScale(scheme='Greens')

# 3. axis 
c_ax = bqplot.ColorAxis(scale=col_sc,
                       orientation='vertical',
                             side='right')

# 4. Mark -- heatmap using our colors to map to our data
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc})

# 5. skipping interactions

# finally: figure
fig = bqplot.Figure(marks=[heat_map], axes=[c_ax]) # added the colorbar to our Figure
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Greens'), side='right')], fig_margin={…

In [41]:
bqplot.OrdinalScale?

In [45]:
# 2 -- scales (just off with only color)
col_sc = bqplot.ColorScale(scheme='Greens')
# ordinal scales for x/y bins
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. axis 
c_ax = bqplot.ColorAxis(scale=col_sc,
                       orientation='vertical',
                             side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark -- heatmap using our colors to map to our data
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc})

# 5. skipping interactions

# finally: figure
fig = bqplot.Figure(marks=[heat_map], axes=[c_ax, x_ax,y_ax]) # added the colorbar to our Figure
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Greens'), side='right'), Axis(scale=Or…

In [47]:
bqplot.GridHeatMap?

In [48]:
# 2 -- scales (just off with only color)
col_sc = bqplot.ColorScale(scheme='Greens')
# ordinal scales for x/y bins
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. axis 
c_ax = bqplot.ColorAxis(scale=col_sc,
                       orientation='vertical',
                             side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark -- heatmap using our colors to map to our data
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 
                                                 'row':y_sc, 
                                                 'column':x_sc})

# 5. skipping interactions

# finally: figure
fig = bqplot.Figure(marks=[heat_map], axes=[c_ax, x_ax,y_ax]) # added the colorbar to our Figure
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Greens'), side='right'), Axis(scale=Or…

In [50]:
# 2 -- scales (just off with only color)
col_sc = bqplot.ColorScale(scheme='Greens')
# ordinal scales for x/y bins
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()
#x_sc = bqplot.LinearScale()
#y_sc = bqplot.LinearScale()

# 3. axis 
c_ax = bqplot.ColorAxis(scale=col_sc,
                       orientation='vertical',
                             side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark -- heatmap using our colors to map to our data
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 
                                                 'row':y_sc, 
                                                 'column':x_sc})

# 5. skipping interactions

# finally: figure
fig = bqplot.Figure(marks=[heat_map], axes=[c_ax, x_ax,y_ax]) # added the colorbar to our Figure
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Greens'), side='right'), Axis(scale=Or…

In [56]:
# 2 -- scales (just off with only color)
col_sc = bqplot.ColorScale(scheme='Greens')
# ordinal scales for x/y bins
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. axis 
c_ax = bqplot.ColorAxis(scale=col_sc,
                       orientation='vertical',
                             side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark -- heatmap using our colors to map to our data
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 
                                                 'row':y_sc, 
                                                 'column':x_sc},
                              interactions={'click':'select'},
                             selected_style={'fill':'magenta'})

# 5. interactions happened in the mark call itself!

# finally: figure
fig = bqplot.Figure(marks=[heat_map], axes=[c_ax, x_ax,y_ax]) # added the colorbar to our Figure
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Greens'), side='right'), Axis(scale=Or…

In [52]:
bqplot.GridHeatMap?

In [53]:
heat_map.keys

['_model_module',
 '_model_module_version',
 '_model_name',
 '_view_count',
 '_view_module',
 '_view_module_version',
 '_view_name',
 'anchor_style',
 'apply_clip',
 'color',
 'column',
 'column_align',
 'display_format',
 'display_legend',
 'enable_hover',
 'font_style',
 'interactions',
 'labels',
 'null_color',
 'opacity',
 'preserve_domain',
 'row',
 'row_align',
 'scales',
 'scales_metadata',
 'selected',
 'selected_style',
 'stroke',
 'tooltip',
 'tooltip_location',
 'tooltip_style',
 'unselected_style',
 'visible']

In [58]:
heat_map.selected

array([[0, 0]])

In [59]:
def on_selected(change):
    print(change)

In [ ]:
# 2 -- scales (just off with only color)
col_sc = bqplot.ColorScale(scheme='Greens')
# ordinal scales for x/y bins
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. axis 
c_ax = bqplot.ColorAxis(scale=col_sc,
                       orientation='vertical',
                             side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark -- heatmap using our colors to map to our data
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 
                                                 'row':y_sc, 
                                                 'column':x_sc},
                              interactions={'click':'select'},
                             selected_style={'fill':'magenta'})

# 5. specify what happens when a s

# finally: figure
fig = bqplot.Figure(marks=[heat_map], axes=[c_ax, x_ax,y_ax]) # added the colorbar to our Figure
fig