# In Class Notebook, Week 07

You can always paste the URL of this notebook (https://github.com/UIUC-iSchool-DataViz/is445_spring2022/blob/master/week07/inClass_week07.ipynb ) into the nbviewer interface for a plain-text rendering:

https://kokes.github.io/nbviewer.js/viewer.html

In [1]:
# import our usual things
import pandas as pd
import bqplot 
import numpy as np
import ipywidgets
import matplotlib.pyplot as plt

In [2]:
data = np.random.random((10,10,20))

In [3]:
data.shape

(10, 10, 20)

In [4]:
data[0,0,:]

array([0.07119276, 0.5339507 , 0.80583913, 0.80294036, 0.41181973,
       0.55648532, 0.81195724, 0.69063172, 0.21087759, 0.38714765,
       0.33739521, 0.91308073, 0.08896405, 0.45384509, 0.43151658,
       0.80063635, 0.07901114, 0.88916352, 0.50246675, 0.19728234])

In [5]:
myLabel = ipywidgets.Label()

In [10]:
myLabel.value = str(data[0,0,:].mean())

In [9]:
myLabel

Label(value='[[0.4988102  0.50040233 0.60487685 0.52798817 0.56697864 0.56730042\n  0.58249943 0.51037515 0.60…

In [11]:
data.mean(axis=2).shape # taking a mean along the "Z" or "3rd" axis

(10, 10)

In [14]:
data.mean(axis=0).shape

(10, 20)

In [15]:
data.mean(axis=1).shape

(10, 20)

In [12]:
# reminder of what a "on selection" function looks like
def on_selected(change):
    #print(change)
    #print(change['owner'])
    if len(change['owner'].selected) == 1: # only allow user to select one bin at a time
        i,j = change['owner'].selected[0]
        print(i,j)

In [13]:
# 1. data (random dataset)

#2. Scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. axis
ax_col = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
ax_x = bqplot.Axis(scale=x_sc)
ax_y = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark (heatmap)
heat_map = bqplot.GridHeatMap(color=data.mean(axis=2),
                              scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                              interactions={'click':'select'},
                              selected_style={'fill':'magenta'})

# 5. interaction, cont.
heat_map.observe(on_selected,'selected')

# combine into a figure
fig = bqplot.Figure(marks=[heat_map],axes=[ax_col, ax_x, ax_y])

# Finally dashboard
myDashboard = ipywidgets.VBox([myLabel,fig])
myDashboard

5 2
1 1
2 3
0 0
0 1
0 2


In [16]:
# reminder of what a "on selection" function looks like
def on_selected(change):
    #print(change)
    #print(change['owner'])
    if len(change['owner'].selected) == 1: # only allow user to select one bin at a time
        i,j = change['owner'].selected[0]
        #print(i,j)
        v = data[i,j,:].mean()
        myLabel.value = 'Mean Data Value for Selection=' + str(v)

In [17]:
# 1. data (random dataset)

#2. Scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. axis
ax_col = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
ax_x = bqplot.Axis(scale=x_sc)
ax_y = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark (heatmap)
heat_map = bqplot.GridHeatMap(color=data.mean(axis=2),
                              scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                              interactions={'click':'select'},
                              selected_style={'fill':'magenta'})

# 5. interaction, cont.
heat_map.observe(on_selected,'selected')

# combine into a figure
fig = bqplot.Figure(marks=[heat_map],axes=[ax_col, ax_x, ax_y])

# Finally dashboard
myDashboard = ipywidgets.VBox([myLabel,fig])
myDashboard

In [18]:
# 1. data
i,j=0,0

data[i,j,:]

array([0.07119276, 0.5339507 , 0.80583913, 0.80294036, 0.41181973,
       0.55648532, 0.81195724, 0.69063172, 0.21087759, 0.38714765,
       0.33739521, 0.91308073, 0.08896405, 0.45384509, 0.43151658,
       0.80063635, 0.07901114, 0.88916352, 0.50246675, 0.19728234])

In [19]:
# 2. scales
x_sch = bqplot.LinearScale()
y_sch = bqplot.LinearScale()

# 3. Axis
x_axh = bqplot.Axis(scale=x_sch, label='Value of 3rd Axis')
y_axh = bqplot.Axis(scale=y_sch, label='Frequency', orientation='vertical')

In [20]:
bqplot.Hist?

In [21]:
# 4. Mark
hist = bqplot.Hist(sample=data[i,j,:], scales={'sample':x_sch, 'count':y_sch}, bins=5)

In [22]:
# 5. Interactions here (but none yet!)

# finally a figure
figh = bqplot.Figure(marks=[hist], axes=[x_axh, y_axh])
figh

Figure(axes=[Axis(label='Value of 3rd Axis', scale=LinearScale(), side='bottom'), Axis(label='Frequency', orie…

In [23]:
hist.keys

['_model_module',
 '_model_module_version',
 '_model_name',
 '_view_count',
 '_view_module',
 '_view_module_version',
 '_view_name',
 'apply_clip',
 'bins',
 'colors',
 'count',
 'display_legend',
 'enable_hover',
 'interactions',
 'labels',
 'midpoints',
 'normalized',
 'opacities',
 'preserve_domain',
 'sample',
 'scales',
 'scales_metadata',
 'selected',
 'selected_style',
 'stroke',
 'tooltip',
 'tooltip_location',
 'tooltip_style',
 'unselected_style',
 'visible']

In [24]:
hist.sample

array([0.07119276, 0.5339507 , 0.80583913, 0.80294036, 0.41181973,
       0.55648532, 0.81195724, 0.69063172, 0.21087759, 0.38714765,
       0.33739521, 0.91308073, 0.08896405, 0.45384509, 0.43151658,
       0.80063635, 0.07901114, 0.88916352, 0.50246675, 0.19728234])

In [25]:
# ######### GRID HEAT MAP #########
# Left, the driver of changes

#2. Scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. axis
ax_col = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
ax_x = bqplot.Axis(scale=x_sc)
ax_y = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark (heatmap)
heat_map = bqplot.GridHeatMap(color=data.mean(axis=2),
                              scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                              interactions={'click':'select'},
                              selected_style={'fill':'magenta'})

# 5. interaction, cont.
######heat_map.observe(on_selected,'selected')

# combine into a figure
fig = bqplot.Figure(marks=[heat_map],axes=[ax_col, ax_x, ax_y])

In [26]:
########## HISTOGRAM ########
# 2. scales
x_sch = bqplot.LinearScale()
y_sch = bqplot.LinearScale()

# 3. Axis
x_axh = bqplot.Axis(scale=x_sch, label='Value of 3rd Axis')
y_axh = bqplot.Axis(scale=y_sch, label='Frequency', orientation='vertical')

# 4. Mark
hist = bqplot.Hist(sample=data[i,j,:], scales={'sample':x_sch, 'count':y_sch}, bins=5)

# finally a figure
figh = bqplot.Figure(marks=[hist], axes=[x_axh, y_axh])

In [27]:
myLabel = ipywidgets.Label()

In [28]:
# Function defining interactions between all dashboard elements
def on_selected(change):
    if len(change['owner'].selected) == 1: # only allow user to select one bin at a time
        i,j = change['owner'].selected[0]
        v = data[i,j,:].mean()
        myLabel.value = 'Mean Data Value for Selection=' + str(v)
        hist.sample = data[i,j,:]

In [29]:
# make sure we have heatmap OBSERVE with this function
heat_map.observe(on_selected, 'selected')

In [33]:
# make a dashboard!
fig.layout.min_width='400px'
figh.layout.min_width='400px'

figures = ipywidgets.HBox([fig,figh])
myDashboard = ipywidgets.VBox([myLabel, figures])
myDashboard

In [35]:
hist.keys

['_model_module',
 '_model_module_version',
 '_model_name',
 '_view_count',
 '_view_module',
 '_view_module_version',
 '_view_name',
 'apply_clip',
 'bins',
 'colors',
 'count',
 'display_legend',
 'enable_hover',
 'interactions',
 'labels',
 'midpoints',
 'normalized',
 'opacities',
 'preserve_domain',
 'sample',
 'scales',
 'scales_metadata',
 'selected',
 'selected_style',
 'stroke',
 'tooltip',
 'tooltip_location',
 'tooltip_style',
 'unselected_style',
 'visible']

In [36]:
hist.colors

['steelblue']

In [38]:
hist.colors='cyan'

In [39]:
hist.bins

5

In [40]:
hist.bins=10

In [41]:
bins_slider = ipywidgets.IntSlider(min=1,max=data.shape[2],value=5)

In [42]:
bins_slider

IntSlider(value=5, max=20, min=1)

In [43]:
hist.bins # histogram attribute/trait of bins

10

In [44]:
bins_slider.value # slider attribute/trait

14

In [45]:
ipywidgets.jslink((bins_slider,'value'), (hist,'bins'))

Link(source=(IntSlider(value=14, max=20, min=1), 'value'), target=(Hist(colors=['cyan'], count=array([4., 2., …

In [46]:
controls = ipywidgets.HBox([myLabel, bins_slider])
figures = ipywidgets.HBox([fig,figh])
myDashboard = ipywidgets.VBox([controls,figures])

fig.layout.min_width='400px'
figh.layout.min_width='400px'

myDashboard

## Dashboards with "real" data

In [47]:
ufos = pd.read_csv("https://uiuc-ischool-dataviz.github.io/spring2019online/week04/data/ufo-scrubbed-geocoded-time-standardized-00.csv",
                  names = ["date", "city", "state", "country",
                          "shape", "duration_seconds", "duration",
                          "comment", "report_date", 
                           "latitude", "longitude"],
                  parse_dates = ["date", "report_date"])

In [48]:
len(ufos)

80332

In [50]:
nsamples = 1000 # downsample to this range
downSampleMask = np.random.choice(range(len(ufos)-1),nsamples,replace=False)
downSampleMask

array([34800, 54423, 57542, 42394, 16450,   834, 27375, 47840, 52116,
        2264, 18220, 50522,  5213, 12226, 35957, 16332, 62667,  4983,
       72779, 20586, 70062, 67307, 15606,  8824, 47485, 42790, 54367,
       42295, 70307, 26885,  3840, 64105, 18932, 78861, 21018, 50512,
       60620, 25942, 36038, 16287, 31084, 12158, 59253, 42564, 78305,
       47709, 64004,  6235, 12411,  1881, 47328, 19263, 77113, 15708,
       10539,  4906,   957, 11361, 41735, 59306, 36550, 79422, 27605,
        9618, 12054, 28167, 72229, 38594, 72087, 59846,  9721, 36197,
       57403, 79776,   722, 58278, 26000, 20419, 46731, 13170, 70457,
       59473, 36470, 10288, 27324, 31642, 65862, 64405, 64381, 43322,
       41747,  1424, 78197, 71391, 44473, 26836, 37756, 20956,  3824,
       71445, 46395, 70948, 14170, 24573, 69851,  8554, 27167, 70417,
       68257,  9581, 50912, 17936, 69632, 33884, 19078, 41782, 10278,
       25803,  6561, 75380, 12627, 71702, 29068, 69727, 20618, 74032,
       68406,  3649,

In [51]:
ufosDS = ufos.loc[downSampleMask]

In [52]:
ufosDS

date                       city state country     shape  \
34800 2006-03-05 14:00:00  stryker (near)  (nw ohio)    oh      us      disk   
54423 1999-06-09 23:43:00                 sacramento    ca      us     light   
57542 2003-07-17 01:15:00           terrace (canada)    bc      ca     light   
42394 1991-05-15 04:05:00          sparwood (canada)    bc     NaN     light   
16450 2007-11-09 18:30:00               indian trail    nc      us     light   
...                   ...                        ...   ...     ...       ...   
49322 2006-06-15 15:00:00                     fallon    nv      us    sphere   
11155 2009-01-01 19:00:00                    concord    ca      us   unknown   
67852 2012-08-19 22:15:00                     cougar    wa      us    circle   
22286 2007-01-24 16:48:00                    spokane    wa      us  triangle   
2624  2010-10-17 04:00:00                  santa ana    ca      us     light   

       duration_seconds                duration  \
34800              30.0         appx 30 seconds   
54423               5.0               5 seconds   
57542             300.0                 5 mins.   
42394             360.0             5-6 minutes   
16450               2.0         about 2 seconds   
...                 ...                     ...   
49322            1800.0             30 minutes+   
11155            7200.0               1-2 hours   
67852             300.0               5 minutes   
22286              60.0  1 minute approximately   
2624              120.0                   2 min   

                                                 comment report_date  \
34800  Saw a floating object in the sky for about 30 ...  2006-03-11   
54423  Orange-white light traveling approx. from Sout...  1999-06-23   
57542  HBCCUFO CANADIAN REPORT:  Object/Light explode...  2003-07-23   
42394  I observed  three stationary interconected lig...  2005-12-16   
16450  a bright red light seen to grow in size and in...  2007-11-28   
...                                                  ...         ...   
49322  UFO sighting east of Fallon&#44 NV&#44 at Navy...  2012-12-20   
11155  Regular&#44 almost nightly sightings of bright...  2009-03-19   
67852  Saw to bright white circular/spherical shapes ...  2012-09-24   
22286  January 24&#44 2007&#44 flying West to East ov...  2008-06-12   
2624   Green and Blue lights in the sky followed by t...  2010-11-21   

        latitude   longitude  
34800  41.503611  -84.414167  
54423  38.581667 -121.493333  
57542  54.500000 -128.583333  
42394  49.731705 -114.887624  
16450  35.076667  -80.669444  
...          ...         ...  
49322  39.473611 -118.776389  
11155  37.978056 -122.030000  
67852  46.051667 -122.298333  
22286  47.658889 -117.425000  
2624   33.745556 -117.866944  

[1000 rows x 11 columns]

In [53]:
# 1. let's try bqplot with a scatter plot of this data (downsampled for now)

# 2. scales
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

# 3. axis
x_ax = bqplot.Axis(scale=x_sc,label='Longitude')
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical', label='Latitude')

# 4. marks
scatters = bqplot.Scatter(x=ufosDS['longitude'], y=ufosDS['latitude'], 
                         scales={'x':x_sc, 'y':y_sc})

# figure
fig = bqplot.Figure(marks=[scatters], axes=[x_ax,y_ax])
fig

Figure(axes=[Axis(label='Longitude', scale=LinearScale()), Axis(label='Latitude', orientation='vertical', scal…

In [55]:
# 1. let's try bqplot with a scatter plot of this data (downsampled for now)

# 2. scales
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()
col_sc = bqplot.ColorScale()

# 3. axis
x_ax = bqplot.Axis(scale=x_sc,label='Longitude')
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical', label='Latitude')
col_ax = bqplot.ColorAxis(scale=col_sc, label='Duration in seconds', orientation='vertical', side='right')

# 4. marks
scatters = bqplot.Scatter(x=ufosDS['longitude'], y=ufosDS['latitude'], color=ufosDS['duration_seconds'],
                         scales={'x':x_sc, 'y':y_sc, 'color':col_sc})

# figure
fig = bqplot.Figure(marks=[scatters], axes=[x_ax,y_ax,col_ax])
fig

Figure(axes=[Axis(label='Longitude', scale=LinearScale()), Axis(label='Latitude', orientation='vertical', scal…

In [57]:
# 1. let's try bqplot with a scatter plot of this data (downsampled for now)

# 2. scales
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()
col_sc = bqplot.ColorScale()

# 3. axis
x_ax = bqplot.Axis(scale=x_sc,label='Longitude')
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical', label='Latitude')
col_ax = bqplot.ColorAxis(scale=col_sc, label='log(seconds)', orientation='vertical', side='right')

# 4. marks
scatters = bqplot.Scatter(x=ufosDS['longitude'], y=ufosDS['latitude'], color=np.log10(ufosDS['duration_seconds']),
                         scales={'x':x_sc, 'y':y_sc, 'color':col_sc})

# figure
fig = bqplot.Figure(marks=[scatters], axes=[x_ax,y_ax,col_ax])
fig

Figure(axes=[Axis(label='Longitude', scale=LinearScale()), Axis(label='Latitude', orientation='vertical', scal…

In [59]:
def generate_histogram_from_lat_long(ufos, nlong=20, nlat=20, longmin=-150, longmax=150,
                                     latmin=-40, latmax=70,
                                     takeLog=True):
    long_bins = np.linspace(longmin, longmax, nlong+1)
    lat_bins = np.linspace(latmin, latmax, nlat+1)
    hist2d, long_edges, lat_edges = np.histogram2d(ufos['longitude'], 
                                                   ufos['latitude'], 
                                                   weights=ufos['duration_seconds'],
                                                  bins = [long_bins,lat_bins])
    hist2d = hist2d.T
    if takeLog:
        hist2d[hist2d <= 0] = np.nan # set zeros to NaNs
        # then take log
        hist2d = np.log10(hist2d)
    long_centers = (long_edges[:-1] + long_edges[1:]) / 2
    lat_centers = (lat_edges[:-1] + lat_edges[1:]) / 2
    return hist2d, long_centers, lat_centers, long_edges, lat_edges

In [60]:
hist2d, long_centers, lat_centers, long_edges, lat_edges = generate_histogram_from_lat_long(ufos)

In [63]:
hist2d.shape

(20, 20)

In [64]:
long_centers

array([-142.5, -127.5, -112.5,  -97.5,  -82.5,  -67.5,  -52.5,  -37.5,
        -22.5,   -7.5,    7.5,   22.5,   37.5,   52.5,   67.5,   82.5,
         97.5,  112.5,  127.5,  142.5])

In [65]:
long_edges

array([-150., -135., -120., -105.,  -90.,  -75.,  -60.,  -45.,  -30.,
        -15.,    0.,   15.,   30.,   45.,   60.,   75.,   90.,  105.,
        120.,  135.,  150.])

In [66]:
len(long_centers), len(long_edges)

(20, 21)

In [ ]:
# plot data with grid heat map

# 2. scales
col_sc = bqplot.ColorScale(scheme='RdPu')
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

# 3. axis
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc, label='Longitude')
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical', label='Latitude')

# 4. marks
heat_map = bqplot.GridHeatMap(color=hist2d)